kubevirt/user-guide

- live-migration.md
Document that influencing the migration target via node labels is
possible.
> Add nodeSelector description for Migrations

- SUMMARY.md
- replicaset.md
Document the VirtualMachineReplicaSet
> Replicaset

- access.md
- installation.md
Installation instructions for upcoming release manifests.
> Installation instructions

- live-migration.md
- registry-disk.md
- replicaset.md
- vm-creation.md
> Update VirtualMachine examples to the new API style

- access.md
- installation.md
* Remove traces of SPICE
* Add VNC documentation
* Remove haproxy, virt-api and spice-proxy traces
> Update user-guide to reflect 0.2.0 changes

- SUMMARY.md
- startup-scripts.md
User guide documentation for how to use provide startup scripts to VMs using KubeVirt.
> Startup script user guide documentation

- SUMMARY.md
- machine.md
* virtualization features
* SMBIOS
* Clock
* Timer
> Documenting different hardware configuration aspects

- SUMMARY.md
- assign-vm-node.md
> Document nodeSelector and affinity

- SUMMARY.md
- workloads.md
- workloads/controllers.md
- workloads/virtual-machines.md
> Fill some empty pages

- disks-and-volumes.md
- machine.md
The api-reference moved to a new location
> Fix api-reference location

- installation.md
Instructions for adding SCCs are listed.
> OpenShift section is added to installation.md

- startup-scripts.md
Signed-off-by: Lukianov Artyom <alukiano@redhat.com>
> Add cloud-init clear text example

- installation.md
* adding section about installation from APB
* adding section about kubevirt-ansible
> Extend installation guide with two more options

- vm-presets.md
VirtualMachinePreset user guide
> Add VirtualMachinePreset user guide

- SUMMARY.md
- guest-os-info.md
Added Guest OS info label for Virtual Machine to user guide.
Signed-off-by: Yanir Quinn yquinn@redhat.com
> Guest OS info label for VM

- SUMMARY.md
> SUMMARY: Add Presets entry

- machine.md
> Add a Resources requests and limits section to the machine user-guide

- startup-scripts.md
> Fix wrong registry disk devel tags

- offline-virtual-machine.md
This pull request add the offline virtual machine user guide.
It is still heavy work in progress and place for discussion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/user-guide/9)
> Add OfflineVirtualMachine userguide

- SUMMARY.md
- service.md
Draft the guide. Please kindly review. Thanks @fabiand @vladikr
> Add guide for exposing vm as a service

- vm-presets.md
Examples of how to match multiple VM's using matchLabels and matchExpressions.
> Add Examples demonstrating how Presets can match multiple VMs

- disks-and-volumes.md
Implementation and technical details are described here: https://github.com/kubevirt/kubevirt/pull/694
> Document emptyDisk

- disks-and-volumes.md
> volumes: Note about disk permissions

- README.md
- additional-resources.md
- installation/README.md
- usage.md
- workloads/controllers.md
- workloads/controllers/README.md
- workloads/controllers/virtual-machine-replica-set.md
- workloads/virtual-machines/README.md
- workloads/virtual-machines/assigning-vms-to-nodes.md
- workloads/virtual-machines/creation.md
- workloads/virtual-machines/disks-and-volumes.md
- workloads/virtual-machines/expose-service.md
- workloads/virtual-machines/guest-operating-system-information.md
- workloads/virtual-machines/life-cycle.md
- workloads/virtual-machines/presets.md
- workloads/virtual-machines/startup-scripts.md
- workloads/virtual-machines/virtualized-hardware-configuration.md
A few minor corrections to spelling and grammar. 
Improve readability by adding abbreviations and making them capitalized.
> Minor edits

- service.md
Add LB service and RDP part for exposing service.
@fabiand @vladikr @rmohr please help review. Thanks
> Add LB service and RDP part for exposing service

- index.html
> Disable coverpage for now

- _sidebar.md
- installation/api-validation.md
Documents installation/usage related to KubeVirt PR https://github.com/kubevirt/kubevirt/pull/911
> user guide describing how api validation works

- workloads/controllers/virtual-machine-replica-set.md
> Fix replicaset example

- workloads/virtual-machines/presets.md
Signed-off-by: Stu Gott <sgott@redhat.com>
> Document how to use VirtualMachinePreset exclusions

- _sidebar.md
Signed-off-by: David Vossel <davidvossel@gmail.com>
> Fix dead link in sidebar

- workloads/virtual-machines/startup-scripts.md
@davidvossel directly seeing the secret is also valuable, but it may be easier for people to use the secrets if we show them the high-level k8s command. What do you think?
> Use convenience command for creating the right k8s secret for cloud-init

- workloads/virtual-machines/interfaces-and-networks.md
> network api base

- _sidebar.md
> Introduce interfaces and networks

- workloads/virtual-machines/graphical-and-console-access.md
To help with troubleshooting, one may be interested to the output
and the error messages from `remote-viewer`
> vnc: document how to get more output

- installation/README.md
- workloads/virtual-machines/virtualized-hardware-configuration.md
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
> Add details how to configure hugepages on a VM

- installation/README.md
Signed-off-by: Lukas Bednar <lbednar@redhat.com>
> installation: added kubevirt-apiserver policy

- installation/README.md
We don't support anything else anymore.
> Bump supported k8s version to 1.10

- workloads/virtual-machines/interfaces-and-networks.md
This is to document https://github.com/kubevirt/kubevirt/pull/1213
> Document interface.macAddress

- workloads/virtual-machines/interfaces-and-networks.md
The page was not in line with the rest of documentation, had multiple bugs,
incorrect information, typos, grammar issues.
This patch reworks the structure and contents of the page from the ground up,
with the emphasis on providing timely examples and capturing just the features
that are already implemented.
Fixes #91
> Refresh documentation on network connectivity

- workloads/virtual-machines/virtualized-hardware-configuration.md
- host-model
- host-passthrough
Do not merge until https://github.com/kubevirt/kubevirt/pull/1345.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
> Documentation for CPU model special cases

- workloads/virtual-machines/graphical-and-console-access.md
Reverts kubevirt/user-guide#83
> Revert "Note that client certs are required for stream api "

- workloads/virtual-machines/virtualized-hardware-configuration.md
Document how to create headless VMIs.
Resolves https://github.com/kubevirt/kubevirt/issues/1136
> Document autoattachGraphicsDevice

- _sidebar.md
- workloads/virtual-machines/overcommit.md
- workloads/virtual-machines/virtualized-hardware-configuration.md
Describe some ways on how to achieve a higher vmi density by not accounting for the guest overhead.
> Describe MoM-less memory overcommit in KubeVirt

- workloads/virtual-machines/interfaces-and-networks.md
Relevant for PR #1393 : https://github.com/kubevirt/kubevirt/pull/1393
> Documentation for  interface.pciAddress

- workloads/virtual-machines/disks-and-volumes.md
Related to https://github.com/kubevirt/kubevirt/pull/1189
This documents the initial DataVolume integration support with KubeVirt. The documentation is fairly light right now because we're still sorting out cloning. Once CDI gains cloning support, we'll document that here as well.
> Document the initial DataVolume integration support

- workloads/virtual-machines/disks-and-volumes.md
Guideline on how to use configMap and secret in KubeVirt.
Related to https://github.com/kubevirt/kubevirt/pull/1474
> configMap and secret guideline

- _sidebar.md
- misc/monitoring.md
Documentation on how to integrate KubeVirt with Prometheus.
> Add documentation for prometheus monitoring integration

- workloads/virtual-machines/dedicated-cpu.md
Signed-off-by: Stu Gott <sgott@redhat.com>
> Fix minor typo

- workloads/virtual-machines/disks-and-volumes.md
Documentation for https://github.com/kubevirt/kubevirt/pull/1480
> Documentation for IOThreads feature

- installation/README.md
Signed-off-by: karmab <karimboumedhel@gmail.com>
> Use correct config map

- workloads/controllers/virtual-machine-replica-set.md
Make clear that VMIRS can corrupt disks if you are not cautious.
> Add data corruption documentation to VMIRS

- workloads/virtual-machines/disks-and-volumes.md
Documents https://github.com/kubevirt/kubevirt/pull/1562
> Document usage of the BlockMultiQueue feature

- _sidebar.md
- workloads/virtual-machines/unresponsive-nodes.md
Document how KubeVirt behaves in case issues on the node appear.
> Document node problem behaviour

- workloads/virtual-machines/interfaces-and-networks.md
The support for virtio-net multiqueue feature has been recently merged in https://github.com/kubevirt/kubevirt/pull/1606
This change provides some additional documentation about the feature
> document the virtio-net multiqueue

- workloads/virtual-machines/presets.md
Signed-off-by: imjoey <majunjiev@gmail.com>
> Fix minor typos in Presets doc

- workloads/virtual-machines/vmctl.md
Documentation covering what vmctl is and how it can be used.
> Document vmctl overview and usage

- installation/README.md
I'm guessing you don't really want people installing 0.4.0 anymore.
> Use latest release

- workloads/virtual-machines/interfaces-and-networks.md
some minor fixes from review of PR #144
> fixes from PR #144

- workloads/virtual-machines/vmctl.md
Signed-off-by: Stu Gott <sgott@redhat.com>
> Add clarifications to vmctl examples and usage

- workloads/virtual-machines/interfaces-and-networks.md
This is to document the new mode added in:
https://github.com/kubevirt/kubevirt/pull/1625
> Document `sriov` interface mode

- workloads/virtual-machines/disks-and-volumes.md
> Added note about tolerating smaller PVs, and use links for disk/volume types

- .aspell.en.pws
- workloads/controllers/virtual-machine-replica-set.md
- workloads/controllers/virtual-machine.md
- workloads/virtual-machines/creation.md
- workloads/virtual-machines/disks-and-volumes.md
- workloads/virtual-machines/dns.md
- workloads/virtual-machines/expose-service.md
- workloads/virtual-machines/startup-scripts.md
Rename the registryDisk to containerDisk.
Fixes: kubevirt/kubevirt#1308
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/user-guide/155)
> Rename registryDisk to containerDisk

- .gitignore
- _topic_map.yml
- release-notes/changelog.adoc
- release-notes/update_changelog.sh
This adds a release changelog to the user-guide.
Introducing a release notes topic
> With changelog

- creating-virtual-machines/intro.adoc
> Fix a small VM formatting error

- creating-virtual-machines/interfaces-and-networks.adoc
Added masquerade binding mechanism to the user guide documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/user-guide/183)
> Added masquerade documentation

- administration/api-validation.adoc
- administration/image-upload.adoc
- architecture/virtual-machine.adoc
- creating-virtual-machines/dedicated-cpu.adoc
- creating-virtual-machines/disks-and-volumes.adoc
- creating-virtual-machines/guest-operating-system-information.adoc
- creating-virtual-machines/intro.adoc
- creating-virtual-machines/presets.adoc
- creating-virtual-machines/probes.adoc
- creating-virtual-machines/startup-scripts.adoc
- creating-virtual-machines/virtio-win.adoc
- creating-virtual-machines/virtualized-hardware-configuration.adoc
- templates/common-templates.adoc
- templates/using-templates.adoc
- using-virtual-machines/assigning-vms-to-nodes.adoc
- using-virtual-machines/dns.adoc
- using-virtual-machines/expose-service.adoc
- using-virtual-machines/overcommit.adoc
- using-virtual-machines/virtual-machine-replica-set.adoc
This updates our documentation to reflect the v1alpha3 API changes.
> V1alpha3 related updates

- templates/common-templates.adoc
Add vm.cnv.io/template-namespace label info 
Related to kubevirt/web-ui#133
> Add namespace label description for templates

- creating-virtual-machines/startup-scripts.adoc
This adds documentation for the changes to be merged in https://github.com/kubevirt/kubevirt/pull/1806
> Update user guide for new cloud-init network-config support.

- creating-virtual-machines/virtualized-hardware-configuration.adoc
Adds documentation showcasing UEFI support.
> Add UEFI/OVMF bootloader documentation

- templates/using-templates.adoc
Update document workloads/templates/vm-creation.md - it was outdated
> up to date document workloads/templates/vm-creation.md

- administration/monitoring.adoc
This PR documents the user-facing changes added by the VM metrics, introduced in kubevirt by https://github.com/kubevirt/kubevirt/pull/1840
> monitoring: document the VM metrics

- creating-virtual-machines/virtualized-hardware-configuration.adoc
This PR introduces tablet device.
Merge after this [PR](https://github.com/kubevirt/kubevirt/pull/1987) is merged
> add tablet input device

- creating-virtual-machines/virtualized-hardware-configuration.adoc
Added a new section for CPU features (flags).
This is based on https://github.com/kubevirt/kubevirt/pull/1978
> Add user guide section for CPU features.

- creating-virtual-machines/virtualized-hardware-configuration.adoc
This PR introduces default-cpu-model
Related to: https://github.com/kubevirt/kubevirt/pull/2028
> add default cpu model

- templates/common-templates.adoc
- templates/using-templates.adoc
This PR replaces generic type of workload with server workload. 
Based on this PR: https://github.com/kubevirt/common-templates/pull/55
@MarSik please review
> replaced generic workload with server workload in templates

- .aspell.en.pws
- creating-virtual-machines/disks-and-volumes.adoc
Signed-off-by: Stefan Hajnoczi <stefanha@redhat.com>
> Fix PersistentVolumeClaim typos

- creating-virtual-machines/guest-operating-system-information.adoc
Document the new feature gate and its purposes.
> hyperv: docs for https://github.com/kubevirt/kubevirt/pull/2083

- .travis.yml
Don't waste time/resources on ruby document installs.
> Don't waste time/resources on ruby document installs.

- _topic_map.yml
- administration/device-plugins.adoc
Instructions on how to manipulate the number of available devices using the --max-devices flag.
> Add instructions regarding virt-handler device plugins

- release-notes/changelog.adoc
- release-notes/update_changelog.sh
> changelog: Add up to v0.15.0

- _distro_map.yml
> Builds docs for branches

- .travis.yml
- _distro_map.yml
Adding this prior to the release of 0.16 in order to prepare multiple release docs
> Add release-0.16

- creating-virtual-machines/interfaces-and-networks.adoc
User guide update for https://github.com/kubevirt/kubevirt/pull/1924
> Add multus as default pod network example.

- templates/common-templates.adoc
trivial rename for consistency
> templates: examples: cnv.io -> kubevirt.io

- _topic_map.yml
- administration/live-migration.adoc
> Document the live migration process

- administration/live-migration.adoc
> document lime migration timeouts configuration

- _topic_map.yml
- web-interface/controlling-vms-modules/restart-vm-web.adoc
- web-interface/controlling-vms-modules/start-vm-web.adoc
- web-interface/controlling-vms-modules/stop-vm-web.adoc
- web-interface/managing-disks-modules/vm-create-disk-web.adoc
- web-interface/managing-disks-modules/vm-delete-disk-web.adoc
- web-interface/managing-nics-modules/vm-create-nic-web.adoc
- web-interface/managing-nics-modules/vm-delete-nic-web.adoc
- web-interface/managing-vms-modules/creating-vm-wizard-web.adoc
- web-interface/managing-vms-modules/creating-vm-yaml-web.adoc
- web-interface/managing-vms-modules/delete-vm-web.adoc
- web-interface/managing-vms-modules/editing-vm-web.adoc
- web-interface/managing-vms-modules/editing-vm-yaml-web.adoc
- web-interface/managing-vms-modules/vm-events-web.adoc
- web-interface/resource-modules/cloud-init-fields-web.adoc
- web-interface/resource-modules/networking-wizard-fields-web.adoc
- web-interface/resource-modules/pxebooting.adoc
- web-interface/resource-modules/storage-wizard-fields-web.adoc
- web-interface/resource-modules/template-wizard-fields-web.adoc
- web-interface/resource-modules/vm-actions-web.adoc
- web-interface/resource-modules/vm-wizard-fields-web.adoc
- web-interface/templates-modules/creating-template-wizard-web.adoc
- web-interface/templates-modules/delete-template-web.adoc
- web-interface/templates-modules/editing-template-yaml-web.adoc
- web-interface/vm-consoles-modules/vm-console-web.adoc
- web-interface/vm-consoles-modules/vm-serial-console-web.adoc
- web-interface/vm-consoles-modules/vm-vnc-console-web.adoc
- web-interface/web-interface.adoc
Add a basic walkthrough for the web interface to include:
* VM/template CRUD
* NICs & disks management
* Console access
> Add basic walkthrough for the web interface

- web-interface/controlling-vms-modules/restart-vm-web.adoc
- web-interface/controlling-vms-modules/start-vm-web.adoc
- web-interface/managing-vms-modules/creating-vm-yaml-web.adoc
- web-interface/managing-vms-modules/editing-vm-yaml-web.adoc
- web-interface/resource-modules/pxebooting.adoc
- web-interface/templates-modules/editing-template-yaml-web.adoc
- web-interface/web-interface.adoc
This PR changes the style of notes to match the rest of the documentation and removes a line that was left in error in the original submission.
> Correct display of notes in web interface walkthrough

- creating-virtual-machines/interfaces-and-networks.adoc
For the most part, stylistic / grammar / typo fixes.
> Cleaned up masquerade interface type docs

- administration/image-upload.adoc
Reusing instructions from Containerized Data Importer's README
> Update Containerized Data Importer version to 1.8

- creating-virtual-machines/disks-and-volumes.adoc
The instructions weren't correct (mainly typo)
> Fix DataVolumes feature gate instructions

- release-notes/changelog.adoc
> Update release notes for v0.16.0 and v0.17.0

- creating-virtual-machines/virtualized-hardware-configuration.adoc
This PR adds documentation for CPUNodeDiscovery feature gate
@MarSik  please review
> added CPUNodeDiscovery feature gate

- administration/intro.adoc
- propose deployment via KubeVirt operator as main flow
- add delete section
> Update intro.adoc with delete instructions

- creating-virtual-machines/disks-and-volumes.adoc
> Fixed anchor links (must be lowercase)

- architecture/virtual-machine.adoc
- creating-virtual-machines/intro.adoc
This PR fixes some broken links as described in https://github.com/kubevirt/user-guide/issues/253
> Fix broken links

- creating-virtual-machines/disks-and-volumes.adoc
- creating-virtual-machines/startup-scripts.adoc
This PR adds documentation for the features added in https://github.com/kubevirt/kubevirt/pull/2120
> Add information about cloud-init ConfigDrive

- creating-virtual-machines/virtualized-hardware-configuration.adoc
Related to kubevirt/kubevirt#1847
> Added a note about RNG device required for latest Fedora images

- administration/monitoring.adoc
Document the new labels we introduced in
https://github.com/kubevirt/kubevirt/pull/2388
> monitoring: document VMI-related labels

- using-virtual-machines/overcommit.adoc
Document [#2304](https://github.com/kubevirt/kubevirt/pull/2304)
> Document cluster memory overcommit

- creating-virtual-machines/dedicated-cpu.adoc
> sidecar feature gate note

- release-notes/changelog.adoc
> changelog: Update to 0.18

- administration/intro.adoc
> Renamed KubeVirt's Ready condition to Available

- release-notes/changelog.adoc
better late than never :)
/cc @stu-gott
> Added v0.19.0 release notes

- creating-virtual-machines/disks-and-volumes.adoc
The Add have to end with / to copy into
folder, otherwise it will create file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/user-guide/282)
> Fix add path for container disk

- release-notes/changelog.adoc
> Added v0.20.0 release notes

- Gemfile
Adds gemfile definition to ease setup by CI systems
> Add Gemfile definition

- welcome/index.adoc
Required for Netlify usage of open source free tier
> Add privacy and netlify statement

- Makefile
Update netlify makefile to process via asciibinder package directly
> Netlify makefile

- Makefile
- administration/intro.adoc
> State that only N-1 to N is supported

- Makefile
Signed-off-by: Pablo Iranzo Gómez <Pablo.Iranzo@gmail.com>
> Remove 'current' branch for avoiding cache issues

- administration/monitoring.adoc
There is no `AdditionalProperties` on the KubeVirt Spec
> Fixed KubeVirt CR monitoring example and formatting

- release-notes/changelog.adoc
- release-notes/update_changelog.sh
Signed-off-by: Oren Cohen <ocohen@redhat.com>
> bug fix - multiple lines in release notes

- architecture/virtual-machine.adoc
Added user-guide for virtctl restart and force restart
Adds docs for: https://github.com/kubevirt/kubevirt/pull/2703
Signed-off-by: Vatsal Parekh <vparekh@redhat.com>
> Added user-guide for virtctl restart

- administration/intro.adoc
Fixes https://github.com/kubevirt/kubevirt/issues/2979 and documents the uninstall workaround in https://github.com/kubevirt/kubevirt/issues/1491#issuecomment-574755869.
> Fix uninstall procedure and add an additional missing cluster requirement

- administration/live-migration.adoc
Indicate PVC requirements
Signed-off-by: Pablo Iranzo Gómez <Pablo.Iranzo@gmail.com>
> State PVC requirements

- administration/image-upload.adoc
Signed-off-by: Michael Henriksen <mhenriks@redhat.com>
This is a rebase of #300 and #306, which GitHub is currently saying is out of date, which might be why it's stuck (is something force-pushing to this repository?)
> update image upload doc to be more DataVolume centric

- _sidebar.md
- usage/life-cycle.md
Better late than never: added doc of virtctl pause and unpause command.
Replaced #314 after markdown migration.
> Added pausing docs

- creation/cloud-init.md
Document https://github.com/kubevirt/kubevirt/pull/3090
> document device role tagging

- usage/life-cycle.md
Signed-off-by: Omer Yahud <oyahud@redhat.com>
> Added documentation for how to rename a VM

- creation/interfaces-and-networks.md
Align with the new IPv6 default CIDR represented at https://github.com/kubevirt/kubevirt/pull/3328
Signed-off-by: Or Mergi <ormergi@redhat.com>
> Update IPv6 addresses

- installation/live-migration.md
> Fix some typos

- creation/interfaces-and-networks.md
Current experimental IPv6 single-stack support is being replaced with
IPv4 and IPv6 dual-stack support.
Signed-off-by: Petr Horacek <phoracek@redhat.com>
> Document dual-stack networking

- creation/probes.md
Document limitations of HTTP / TCP probes on dual stack networking configurations.
> Dual stack probes limitations

- templates/templates.md
Make the a sentence more legible.
Note that issue #343 tracks the bigger problem of having two broken links in this short page.
> templates: fix English

- creation/host-devices.md
This PR provides documentation for Host Devices assignment in Kubevirt
https://github.com/kubevirt/kubevirt/pull/3937
> Document the configuration and assignment of Host Devices

- architecture.md
https://github.com/kubevirt/user-guide/issues/339
> correct delete comment

- README.md
- _sidebar.md
- appendix/appendix.md
- appendix/contributing.md
This pull requests creates a Getting Started page in user-guide so that new users and contributors have a nice itinerary of tasks to complete to get up to speed with the project.
> Create Getting Started page

- creation/interfaces-and-networks.md
Macvtap is now available as a new bind mechanism.
This PRs adds documentation on how to configure a VMI with a macvtap interface.
> Macvtap user guide

- architecture.md
- creation/run-strategies.md
Found these typos while reading the documentation.
Signed-off-by: Jordi Gil <jgil@redhat.com>
> [WIP] Fixed various typos in documentation

- README.md
- appendix/appendix.md
Signed-off-by: Ansi Jain <ansi.jain@india.nec.com>
> Fixed broken links

- creation/interfaces-and-networks.md
Use syntax highlighting and mark headings consistently with #.
Signed-off-by: Petr Horacek <phoracek@redhat.com>
> Unify markdown formatting in network guide

- creation/probes.md
Document the basic usage of watchdogs in kubevirt.
> Document watchdog usage

- architecture.md
Signed-off-by: Antonio Cardace <acardace@redhat.com>
> Fix typo in architecture.md

- usage/graphical-and-console-access.md
Signed-off-by: Vatsal Parekh <vparekh@redhat.com>
> Add documentation for vnc proxy-only mode

- installation/installation.md
added necessary configuration information for a successful install on k3OS bare metal,    
for more context, why this is needed see https://github.com/kubevirt/kubevirt/issues/4992
> added information for k3OS installation

- docs/virtual_machines/startup_scripts.md
Added documentation for the Sysprep API support
This depends on: https://github.com/kubevirt/kubevirt/pull/4921
Signed-off-by: borod108 <bodnopoz@redhat.com>
> Add documentation for Sysprep API support

- docs/operations/node_assignment.md
Add paragraph with descheduler annotation
Signed-off-by: Karel Simon <ksimon@redhat.com>
> Add paragraph with descheduler annotation

- docs/virtual_machines/virtual_machine_instances.md
> Updated Missing Link

- docs/virtual_machines/templates.md
This PR updates part of common-templates documentation, which was outdated. This PR is focusing only on fixing things which are wrong. I am planning to add more documentation with new features in next PRs.
//cc @omeryahud 
Signed-off-by: Karel Simon <ksimon@redhat.com>
> Update outdated documentation for common-templates

- docs/operations/updating_and_deletion.md
We have a new feature that coordinates updating VMIs which has landed in kubevirt that will in the upcoming v0.39.0 release. https://github.com/kubevirt/kubevirt/pull/4686
> Document KubeVirt VMI update automation

- docs/operations/updating_and_deletion.md
- docs/virtual_machines/host-devices.md
- docs/virtual_machines/startup_scripts.md
- Change a ```foo``` to `foo`
- Fix some indented code blocks
Signed-off-by: Jeff Squyres <jeff@squyres.com>
> Minor markdown rendering fixes

- mkdocs.yml
Signed-off-by: Eran Ifrach <eifrach@redhat.com+>
> fixing favicon

- docs/virtual_machines/virtual_hardware.md
update node-labeller documentation
/hold 
Merge only after kubevirt PR https://github.com/kubevirt/kubevirt/pull/4916 is merged
Signed-off-by: Karel Simon <ksimon@redhat.com>
> update node-labeller documentation

- README.md
> Simple link fix in README

- docs/virtual_machines/host-devices.md
Minor text cleanups and clarifications.
Signed-off-by: Jeff Squyres <jsquyres@cisco.com>
> host-devices.md: general text cleanup

- docs/operations/node_overcommit.md
This is a follow up to [1] to document the `cpuAllocationRatio` parameter in KubeVirt CRD
[1] https://github.com/kubevirt/kubevirt/pull/4162
> Document cpuAllocationRatio

- docs/operations/node_overcommit.md
- docs/virtual_machines/host-devices.md
- docs/virtual_machines/virtual_hardware.md
Signed-off-by: Eran Ifrach <eifrach@redhat.com>
> fixing spelling test typos

- docs/operations/containerized_data_importer.md
fixes #334
﻿Signed-off-by: John Herr <joherr@redhat.com>
> added steps to avoid using --uploadproxy-url for issue 334

- docs/virtual_machines/run_strategies.md
Fixes https://github.com/kubevirt/kubevirt/issues/5395
> Fixes https://github.com/kubevirt/kubevirt/issues/5395

- docs/operations/containerized_data_importer.md
> Added certificate information to cdi

- docs/operations/containerized_data_importer.md
That command may not work expectedly.
> Fix command adding entry to hosts file

- docs/virtual_machines/disks_and_volumes.md
Fixes https://github.com/kubevirt/user-guide/issues/443
> Added Note to enable Feature Gate HostDisk

- update_changelog.sh
> Fixed update_changelog.sh master->main

- docs/operations/installation.md
We now release ARM64 developer builds.
> Document ARM developer build installation

- docs/virtual_machines/host-devices.md
Fixes https://github.com/kubevirt/user-guide/issues/460
> Fix spelling error

- docs/virtual_machines/.pages
- docs/virtual_machines/istio_service_mesh.md
> Add user-guide for VMI with Istio

- docs/operations/customize_components.md
Added documentation on the different customization options exposed in kubevirt. 
Fixes https://github.com/kubevirt/user-guide/issues/459
> add user guide for patch and flag customization options

- OWNERS
- Self added as reviewer, approver
- @jobbler as reviewer
> Added reviewers, approver

- docs/virtual_machines/windows_virtio_drivers.md
Fixes https://github.com/kubevirt/user-guide/issues/454
> Updated Links

- docs/virtual_machines/interfaces_and_networks.md
With the introduction on CNAO v0.58, a new `cnv-bridge` CNI plugin is
deployed which can support MAC address spoof-checking.
Relevant information is provided in a new section on how to utilize this
new option.
> interfaces-and-networks: Add a security section with spoof-checking

- docs/architecture.md
> Fix broken architecture graph link

- OWNERS
Ashley is no longer actively reviewing PRs.
> OWNERS: make Ashley an emeritus approver

- OWNERS
Signed-off-by: Chris Callegari <mazzystr@gmail.com>
> Moving codificat/hroyrh to emeritus_approvers...end of an era

- docs/virtual_machines/startup_scripts.md
Adding a note on a caveat when using the Sysprep tool.
Signed-off-by: borod108 <boris.od@gmail.com>
> Improve documentation for Sysprep API

- Makefile
> Adjustments to Makefile

- docs/virtual_machines/startup_scripts.md
initial draft with examples from Dominik Holler
> Imporve sysprep doc

- docs/virtual_machines/.pages
- docs/virtual_machines/numa.md
Documents https://github.com/kubevirt/kubevirt/pull/5846
> Document basic NUMA support

- docs/appendix/contributing.md
Seems weird to participate on Slack Overflow, I assume we meant Slack?
> Typo: Slack vs Stack Overflow

- docs/operations/installation.md
The previous description was out-of-date, and didn't work - direct patches to the virt-handler DaemonSet are reverted by the virt-operator (reported [here](https://kubernetes.slack.com/archives/C8ED7RKFE/p1635892907035500)).
> Update KubeVirt components node placement description

- docs/operations/snapshot_restore_api.md
This is relevant since kubevirt release v0.47
> Edit snapshot doc to updated support of hotplugged disks

- CONTRIBUTING.md
- Makefile
- README.md
- docs/appendix/contributing.md
- docs/operations/activating_feature_gates.md
- docs/operations/containerized_data_importer.md
- docs/operations/installation.md
- docs/operations/unresponsive_nodes.md
- docs/virtual_machines/templates.md
Replace term master with main where possible, updating outdated links
> Remove non inclusive terms

- docs/virtual_machines/guest_agent_information.md
Explain the new field and it's possible values.
Additional:
Fix indentation of status snippets.
Related to https://github.com/kubevirt/kubevirt/pull/6793
> guest_agent_information: Add info about vmi status infoSource

- docs/virtual_machines/presets.md
in conjunction with https://github.com/kubevirt/kubevirt/pull/7143
Signed-off-by: jbpratt <jbpratt78@gmail.com>
> update vmi preset version to v1

- docs/operations/.pages
- docs/operations/mediated_devices_configuration.md
- docs/virtual_machines/host-devices.md
This PR documents the various configuration options of mediated devices in Kubevirt.
* https://github.com/kubevirt/kubevirt/pull/5974
* https://github.com/kubevirt/kubevirt/pull/6345
> Document the configuration of mediated devices

- docs/virtual_machines/disks_and_volumes.md
Document `shareable` option with an example
> add docs for shareable option

- docs/virtual_machines/startup_scripts.md
Signed-off-by: jbpratt <jbpratt78@gmail.com>
> Correct the spacing for device tagging snippet

- docs/operations/live_migration.md
- docs/operations/virtctl_client_tool.md
Also fixed a typo in this page: s/perfomance/performance/
reported by make check_spelling
Signed-off-by: Uri Lublin <uril@redhat.com>
> migration: how to initiate and cancel migrations using virtctl

- docs/virtual_machines/disks_and_volumes.md
Signed-off-by: John Herr <joherr@redhat.com>
Fixes #517
> Fixed feature gate requirement for DV

- docs/virtual_machines/interfaces_and_networks.md
This PR documents IPv6 single stack cluster.
> IPv6 single stack: adding documentation.

- docs/operations/component_monitoring.md
Signed-off-by: bmordeha <bmodeha@redhat.com>
https://github.com/kubevirt/kubevirt/pull/7130
> Add explaination about serviceMonitorNamespace field of kubevirtCR

- docs/operations/installation.md
@dhiller as you suggested in https://groups.google.com/g/kubevirt-dev/c/zXLSZD9m8Jg/m/RHPVCgkjCQAJ .
> update kubernets version dependency

- docs/virtual_machines/.pages
- docs/virtual_machines/confidential_computing.md
Added documentation on how to run a VM with SEV memory encryption.
> Document basic SEV support

- docs/virtual_machines/startup_scripts.md
Links to Window SIM and the answer file references were added to the Sysprep section.
> Add more information about Windows answer files

- docs/architecture.md
- docs/virtual_machines/virtual_machine_instances.md
Signed-off-by: imusmanmalik <usmanmalik@engineer.com>
> docs: Fix typo in architecture and vmi

- docs/operations/memory_dump.md
Signed-off-by: Shelly Kagan <skagan@redhat.com>
> Add documentation for memory dump command

- docs/virtual_machines/virtual_hardware.md
> Add missing Secure Boot documentation

- docs/operations/updating_and_deletion.md
Fix issue https://github.com/kubevirt/kubevirt/issues/8131
Signed-off-by: Simon Yang <yang.chenjun@99cloud.net>
> add delete virt-operator-validator webhook guide

- docs/operations/memory_dump.md
This PR links to another documentation which is on a PR so need it to be merged first: https://github.com/kubevirt/user-guide/pull/549
Signed-off-by: Shelly Kagan <skagan@redhat.com>
> Update memory dump doc with new feature improvements

- docs/virtual_machines/.pages
- docs/virtual_machines/instancetypes.md
- docs/virtual_machines/virtual_machine_instances.md
Introduce docs for the recently renamed instancetype API.
> Add instancetypes documentation

- docs/architecture.md
- docs/virtual_machines/lifecycle.md
See also https://github.com/kubevirt/kubevirt/pull/5723
> life-cycle: Add documentation about force stop

- docs/virtual_machines/startup_scripts.md
userData should start with `#cloud-config` or the parsing will fail.
> Update the cloudInitNoCloud userdata example

- docs/operations/export_api.md
Documentation for the VirtualMachineExport feature including PVC/VMSnapshot/VM export and matching virtctl commands.
Signed-off-by: Alexander Wels <awels@redhat.com>
> VirtualMachineExport documentation

- docs/virtual_machines/tekton_tasks.md
Update create-datavolume name to modify-data-object
Added more description to example pipelines
/hold
Signed-off-by: Karel Šimon <ksimon@redhat.com>
> improve kubevirt tekton tasks documentation

- docs/virtual_machines/interfaces_and_networks.md
Signed-off-by: Michael Sidorov <mixity@yandex.ru>
fixed typo in macvtap conig
> fix typo in macvtap config

- docs/virtual_machines/liveness_and_readiness_probes.md
Add guest-agent exec probes documentation. This documentation is based on the existing one in the kubevirt [repository](https://github.com/kubevirt/kubevirt/blob/main/docs/probes.md).
> docs, probes: Add guest-agent exec probes documentation

- docs/virtual_machines/instancetypes.md
/area instancetype
/cc @akrejcir 
/cc @davidvossel 
This includes a new format for the data stored within the controllerrevision. This is updated in the versioning example.
> Update instancetype docs for version v1alpha2

- docs/virtual_machines/networkpolicy.md
Signed-off-by: deesejohn <deese.john@gmail.com>
> Fix headers and yaml formatting in NetworkPolicy

- docs/architecture.md
- docs/operations/component_monitoring.md
- docs/operations/containerized_data_importer.md
- docs/operations/customize_components.md
- docs/operations/live_migration.md
- docs/operations/node_assignment.md
- docs/operations/node_maintenance.md
- docs/operations/node_overcommit.md
- docs/operations/updating_and_deletion.md
- docs/virtual_machines/dedicated_cpu_resources.md
- docs/virtual_machines/disks_and_volumes.md
- docs/virtual_machines/dns.md
- docs/virtual_machines/guest_agent_information.md
- docs/virtual_machines/guest_operating_system_information.md
- docs/virtual_machines/interfaces_and_networks.md
- docs/virtual_machines/replicaset.md
- docs/virtual_machines/run_strategies.md
- docs/virtual_machines/service_objects.md
- docs/virtual_machines/startup_scripts.md
- docs/virtual_machines/templates.md
- docs/virtual_machines/virtual_hardware.md
- docs/virtual_machines/virtual_machine_instances.md
Signed-off-by: Christopher Negus <striker57@gmail.com>
This PR updates all v1alpha3 references to v1 in the user-guide.
Fixes: #601
@cwilkers
> Change references to v1alpha3 to v1

- docs/virtual_machines/disks_and_volumes.md
Signed-off-by: RahulV <rverma@upchain.com>
Adds `virtIO-FS` user guide.
> Adds virtio-fs user guide

- docs/operations/installation.md
Fixes https://github.com/kubevirt/kubevirt/issues/7473
> Document the support status of AppArmor

- docs/index.md
Fixes: #587 
Signed-off-by: KiranSatyaRaj <kiranjamy20021508@gmail.com>
> Linked kubevirt labs to docs

- docs/.pages
- docs/quickstarts.md
created a new file quickstarts.md and added the quickstart guides to user-guide
Fixes: #588 
Signed-off-by: KiranSatyaRaj <kiranjamy20021508@gmail.com>
> added quickstart guides to ToC

- netlify.toml
Needed to unbreak the user-guide netlify build process (mostly tested...)
> Updates for new netlify image

- Makefile
Hopefully the last update to un-break netlify
> Update Makefile to use latest netlify python ver

- netlify.toml
> Resetting to opt build repo path

- docs/virtual_machines/disks_and_volumes.md
Add an example explaining how to share node directories with VMs using virtiofs. This example is based in this [discussion](https://groups.google.com/g/kubevirt-dev/c/zTnXrjYDDcc).
> virtiofs, hostpath: Add an example for using hostpath in VMs.

- docs/operations/memory_dump.md
Signed-off-by: Shelly Kagan <skagan@redhat.com>
> Update memory dump command with download options

- docs/operations/.pages
- docs/operations/client_passthrough.md
At the moment, only USB Redireciton with usbredir is supported.
Added in https://github.com/kubevirt/kubevirt/pull/4089
> Add client passthrough documentation

- docs/virtual_machines/interfaces_and_networks.md
Add prerequisites for the guest to get the correct MTU
> Add prerequisites for the guest to get the correct MTU

- docs/architecture.md
Signed-off-by: Dharmit Shah <shahdharmit@gmail.com>
Replaced a bunch of `>` with admonitions.
> Adds admonitions to architecture docs

- docs/virtual_machines/interfaces_and_networks.md
> Windows guest non virtio interfaces don't get the correct MTU

- docs/virtual_machines/.pages
- docs/virtual_machines/creating_vms.md
This adds documentation for the virtctl create vm command.
> feat(virtctl): Add documentation for the virtctl create vm command

- docs/virtual_machines/.pages
- docs/virtual_machines/pool.md
This PR adds VirtualMachinePool basic details to the KubeVirt user guide.
Signed-off-by: Marcelo Feitoza Parisi <marcelo@feitoza.com.br>
> VirtualMachinePool Documentation

- docs/release_notes.md
**Description:**
This PR Fixes #657
> Added Kubevirt v0.59.0 release notes

- docs/virtual_machines/disks_and_volumes.md
Removed since v0.51.0 in  https://github.com/kubevirt/kubevirt/pull/6865
> disks-and-volumes: remove reference to floppy

- docs/operations/hotplug_interfaces.md
Add documentation about the Hotplug Network Interfaces feature using live-migration to attache interfaces.
> Document hotplug network interfaces using live migration

- docs/index.md
> Example of on the fly PR

- docs/operations/.pages
Add gitops.md to the .pages file
> fix: Add gitops.md to the .pages file

- docs/virtual_machines/disks_and_volumes.md
Adding documentation for the Persistent Reservation feature added by https://github.com/kubevirt/kubevirt/pull/9177
> Document persistent reservation feature

- docs/operations/hotplug_interfaces.md
The user facing API is the VirtualMachine, it is less common to work with the back-end VirtualMachineInstance object.
Therefore, the example has been adjusted to describe a VM.
In addition, it has been simplified a bit by removing the cloud-init disk/volume.
> hotplug-interfaces: Use VirtualMachine in the example

- docs/operations/.pages
- docs/operations/ksm.md
Add a documentation for ksm, which explain how to enable it and how to use it
> Add documentation for ksm

- docs/virtual_machines/disks_and_volumes.md
Fixed typo:
claimName instead of clainName
> Update disks_and_volumes.md (typo)

- docs/operations/hotplug_interfaces.md
Update the interface hotplug doc with unplug interfaces functionality.
> hotplug interfaces: Add content about interfaces removal

- docs/virtual_machines/tekton_tasks.md
chore: update tekton tasks section
this PR updates links and mentions about TTO (which is deprecated) and replace them with SSP operator
> chore: update tekton tasks section

- docs/virtual_machines/creating_vms.md
- docs/virtual_machines/instancetypes.md
This PR adds a description of the  virtctl create instancetype and virtctl create preference commands.
> Add documentation for virtctl create command

- docs/virtual_machines/disks_and_volumes.md
Add to documentation that writeback is a valid cache mode for disks
Fixes #627
I did some research on the feature, but would appreciate sanity-check from some of the devs that I'm not misleading anybody here.
> Add note about writeback mode in disk cache

- docs/virtual_machines/resources_requests_and_limits.md
> Adjust documentation for auto resource limits

- docs/operations/.pages
- docs/operations/cpu_hotplug.md
Signed-off-by: enp0s3 <ibezukh@redhat.com>
> adding documentation regarding CPU hotplug

- docs/operations/hotplug_interfaces.md
Update the dynamic network section on how to hotplug/unplug interfaces following the changes in Kubevirt.
> Dynamic Networks: Document new API for hotplug/unplug

- docs/virtual_machines/host-devices.md
Hi,
This is related to the feature that is not yet merged: https://github.com/kubevirt/kubevirt/pull/10015
Cheers,
> Add USB pass through documentation

- docs/operations/hotplug_interfaces.md
Following #729, this PR fix's misplaced statements and refine phrasing and formatting.
> Refine dynamic networking doc phrasing and formating

- docs/operations/clone_api.md
VirtualMachineClone phase is more than Progressing and Succeeded.
> Update description for VirtualMachineClone phase

- docs/operations/clone_api.md
As we have add template label and annotation filters and we want to add how to use template label and annotation filters.
> cloneAPI: add how to use template label and annotation filters

- docs/virtual_machines/interfaces_and_networks.md
Reacting after user's feedback.
> Update macvtap docs

- docs/operations/.pages
- docs/operations/memory_hotplug.md
Add user-guide page about memory hotplug.
> Add Memory Hotplug Documentation

- docs/operations/.pages
- docs/operations/deploy_common_instancetypes.md
- docs/operations/feature_gate_status_on_Arm64.md
- docs/virtual_machines/instancetypes.md
This adds instructions which explain how to deploy common-instancetypes.
Fixes #
**Checklist**
```release-note
None
```
> common-instancetypes: Add deployment instructions

- netlify.toml
I was looking at the CI failure at https://github.com/kubevirt/user-guide/pull/751 and it complains about escaping, error is:
```
>   command = "source /opt/buildhome/python3.8/bin/activate; pip3 install mkdocs mkdocs-awesome-pages-plugin mkdocs-material; sed -i "s/site_url: https:\/\/kubevirt.io\/docs/site_url: https:\/\/kubevirt.io\//" /opt/build/repo/mkdocs.yml; sed -i "s/docs_dir: docs/docs_dir:/" /opt/build/repo/mkdocs.yml; echo "*** BEGIN /opt/build/repo/mkdocs.yml ***"; cat /opt/build/repo/mkdocs.yml; echo "*** END /opt/build/repo/mkdocs.yml ***"; mkdocs build -f /opt/build/repo/mkdocs.yml -d /opt/build/repo/site"
^
```
Not easy to see the issue with a huge command line. This PR tries to break it down and fix the issue if any.
**Which …
> netlify: break huge string

- docs/operations/.pages
- docs/operations/hook-sidecar.md
> User guide for hook sidecar

- docs/virtual_machines/host-devices.md
Two patches, one addressing a file-not-found [raised here](https://github.com/kubevirt/kubevirt/issues/10727#issuecomment-1820767861) and Andrews late suggestion [here](https://github.com/kubevirt/user-guide/pull/718/commits/f5532101f958230e5f99260571ccf7f9a0b8fab0#r1366517641).
Cheers,
> Fix file-not-found

- docs/operations/cpu_hotplug.md
> Typo: s/,/./

- docs/virtual_machines/disks_and_volumes.md
Add details that the persistent reservation deploys a privileged component and enables additional privileged operations.
```release-note
NONE
```
> persistent reservation: add security note

- docs/virtual_machines/disks_and_volumes.md
thanks to @alicefr for helping me figure this out.
maybe the example is useful to someone else.
> document an example how to use a static PersistentVolume

- docs/storage/export_api.md
- docs/storage/snapshot_restore_api.md
With KubeVirt 1.3 release, snapshot and export APIs are beta
Fixes #
**Checklist**
```release-note
snapshot and export APIs to beta
```
> snapshot and export APIs to beta

- README.md
- docs/compute/numa.md
Add 'Additional Reading' section to the NUMA page to mention related Kubernetes topics. 
**Which issue(s) this PR fixes** 
Fixes #755 
**Checklist**
```release-note
NONE
```
> NUMA.md add Additional Reading section

- docs/storage/disks_and_volumes.md
- docs/storage/volume_migration.md
Document update volume strategy and volume migration
```release-note
Add documentation for the update volume strategy and volume migration
```
> Document update volume strategy and volume migration

- docs/user_workloads/startup_scripts.md
Fix a yaml example
Fixes #
**Checklist**
```release-note
```
> role tagging: Fix example

- docs/storage/containerized_data_importer.md
Add more virtctl examples and flags, copied from "virtctl upload-image --help".
```release-note
None
```
> docs: update virtctl examples and flags

- docs/compute/memory_hotplug.md
Fixes #
**Checklist**
```release-note
Update memory hotplug user guide
```
> mem-hotplug: update user-guide

- docs/network/interfaces_and_networks.md
rearrange sections such that reading through would be easier, mainly by moving most restiriction and limitations to the bottom. Main sections are: Networks, Interfcaes. Security, Limitations and Known Issues, Additional Notes Later on links will be added from the  sections in the top to their limitations in the bottom
The doc is cluttered and outdated, this PR attempts to modernize it, clean it up and make it easier for users to read through
Fixes #
**Checklist** …
> interfaces and networks: update and cleanup doc

- docs/user_workloads/creating_vms.md
Update the example description to match the latest usage examples in virtctl.
Fixes #
**Checklist**
```release-note
None
```
> creating_vms: Update example description

- docs/cluster_admin/installation.md
It fixes yaml indenting in the installation guide 
```release-note
docs: fix yaml indenting on intallation.md
```
> docs: fix yaml indenting on intallation.md

- docs/compute/live_migration.md
This PR is a follow-up on https://github.com/kubevirt/kubevirt/pull/11833 to document the behavior of the new AllowWorkloadDisruption migration option.
```release-note
NONE
```
> Document the AllowWorkloadDisruption migration option

- docs/user_workloads/accessing_virtual_machines.md
These cleanups bring the documentation in line with the current implementation of ssh and scp in virtctl.
Fixes #
Merge after https://github.com/kubevirt/kubevirt/pull/13939
**Checklist**
```release-note
None
```
> virtctl: Cleanups to accessing VMs with virtctl ssh

- docs/user_workloads/instancetypes.md
Fixes #
**Checklist**
```release-note
NONE
```
> instancetype: Add InstancetypeReferencePolicy docs

- docs/user_workloads/deploy_common_instancetypes.md
The field is actually `enabled` and not `enable` as documented in the API reference guide below:
https://kubevirt.io/api-reference/main/definitions.html#_v1_commoninstancetypesdeployment
Fixes #
**Checklist**
```release-note
NONE
```
> common-instancetypes: Correct spelling, formatting and enabled example

- docs/storage/disks_and_volumes.md
Add documentation for the  supplementalPool iothread policy introduced by https://github.com/kubevirt/kubevirt/pull/13110
```release-note
Add documentation for the supplementalPool iothread policy
```
> Document supplementalPool iothreads policy

- docs/user_workloads/liveness_and_readiness_probes.md
**Which issue(s) this PR fixes** 
Fixes #865 
@orelmisan - I've tested all these so should be all good!
> Fixed broken examples of liveness and readiness probes (#865)

- docs/storage/export_api.md
This Pull Request updates the `vmexport ` docs with new flags and usage examples.
Fixes # https://issues.redhat.com/browse/CNV-45465
```release-note
NONE
```
> Export: Update vmexport docs with new flags

- docs/storage/snapshot_restore_api.md
Added information about the included excluded volumes lists Added information about the snapshot indications and their meanings.
Added a new line after the headline of readiness policies Fix spelling.
```release-note
VMSnapshot: add better documentation on snapshot verification - included,excluded volumes and snapshot indications
```
> VMSnapshot: add better documentation on snapshot verification - included,excluded volumes and snapshot indications
