README.md, access.md, installation.md, live-migration.md, vm-creation.md, vm-life-cycle.md
With the switch from TPRs to CRDs, it is now possible to name our
VirtualMachine object properly while still keeping the nice vm and vms
shortcuts for kubectl.
Stay in sync with https://github.com/kubevirt/kubevirt/pull/452
=> Rename VM to VirtualMachine

SUMMARY.md, registry-disk.md, replicaset.md
Registry Disk user-guide and updates.
Requires https://github.com/kubevirt/kubevirt/pull/460 to be merged first.
=> Registry Disk user-guide update

machine.md
Document that all vms are booted with BIOS and that UEFI is not yet supported.
Signed-off-by: Travis CI <travis@travis-ci.org>
=> Document that all vms are booted with BIOS

machine.md
To help users understand various machine types and ways of configuring
them, we add a simple section (currently only for x86_64 arch)
explaining what machine types are, which machine type does KubeVirt
default to and how to override that default.
Signed-off-by: Martin Polednik <mpolednik@redhat.com>
=> machine: add section about machine type

book.json
On longer documentation pages it is hard to point people to the right section. Let's add the anchors plugin, so that we can share links to headings inside a page.
`gitbook install` will install the plugin. On gitbook.com this happens implicitly.
=> Add anchors to user-guide pages

vm-presets.md
Align existing examples using OS to use the os label (instead of flavor) 
Signed-off-by: Yanir Quinn yquinn@redhat.com
=> Align VM preset examples to use os label

disks-and-volumes.md
KubeVirt now supports ephemeral volumes backed by PVCs. We therefore
add a short text explaining how such volumes are configured and what
their use may be.
=> add section explaining how ephemeral volumes are used

offline-virtual-machine.md
Document changes made to the `virtctl` command from https://github.com/kubevirt/kubevirt/pull/817
=> Change examples of OfflineVM management to favor using vitrctl

access.md
This reflects the changes to RBAC permissions for VM Console/VNC access that are landing as a part of this PR, https://github.com/kubevirt/kubevirt/pull/770
=> VNC/Console RBAC Role documentation

_sidebar.md, workloads/virtual-machines/node-eviction.md
This documents the process of how to drain a node running VirtualMachines. It also outlines the expected behavior of what happens to VirtualMachines after being evicted from a node.
=> VirtualMachine node eviction documentation

_sidebar.md, workloads/controllers/offline-virtual-machine.md
* Reintroduces OVM documentation, since it seems like it was deleted when we moved to docsify.
* Updates the documentation to reflect changes in https://github.com/kubevirt/kubevirt/pull/973
=> Reintroduce and update OfflineVirtualMachine documentation

workloads/controllers/README.md, workloads/virtual-machines/expose-service.md
Focus more on how to expose the VM, than on how to expose the underlying pod. Tries to address confusions on how well we can integrate with core-services, although we are using CRDs and not an alternative container runtime for virtualization workloads.
=> Update service integration documentation

authorization.md
This documents how users can extend the default Kubernetes roles using the KubeVirt roles. This allows users who already have admin, edit, or view permissions within the cluster to automatically receive the equivalent kubevirt permissions as well.
=> using aggregated cluster roles

workloads/virtual-machines/disks-and-volumes.md
Fixes #73 
The reference pointed to a dockerhub organization `kubevirt.io`, but our organization is named `kubevirt`.
=> Fix reference to kubevirt/registrydisk base image

workloads/virtual-machines/creation.md
Add a  more recent example to the creation page. Use only ephemeral storage to avoid the need of a cluster provisioner and finally add some links to follow-up topics.
Fixes #64.
=> Fix create example

workloads/virtual-machines/graphical-and-console-access.md
If people use ssh to connect to a remote machine where virtctl is then
used, they need to forward their X session or proxy the apiserver.
=> Document ways on how to forward the VNC session to your machine

workloads/virtual-machines/creation.md
Fixes https://github.com/kubevirt/kubevirt.github.io/issues/57.
Format api-reference link on creation page accordingly.
=> Fix broken api-reference link

workloads/virtual-machines/interfaces-and-networks.md
With https://github.com/kubevirt/kubevirt/pull/1167 merged, kubevirt will
support model attribute for interfaces (before the PR, it was supported via
annotations but we never captured that in documentation, so no accommodation
needed).
=> Document the new `model` interface attribute

installation/README.md
Add a note about supported container runtimes.
Fixes: kubevirt/kubevirt#896
=> Add note about CRIO

workloads/virtual-machines/virtualized-hardware-configuration.md
We don't support cpu-mode right now. Only `model`. If not specified, KubeVirt falls back to host-model.
Aligns the documentation with the code. Related to https://github.com/kubevirt/kubevirt/issues/1340
=> Fix cpu-model documentation

workloads/virtual-machines/interfaces-and-networks.md
The previous attempt [1] to fix the MAC address format in the table
resulted in spurious backslashes in the result output.
This is the second attempt to make the MAC addresses look as they should
in the output. Now instead of escapes, we use ``-strings.
This new change is now validated with the actual web server running. It
works as expected.
[1] https://github.com/kubevirt/user-guide/pull/103
=> Fixed MAC address format in regular text (2nd attempt)

workloads/virtual-machines/interfaces-and-networks.md
The field will disable automatic attachment of a VMI without explicit pod interface definition to the pod network.
This PR is to document the field added in: https://github.com/kubevirt/kubevirt/pull/1324
=> Document autoattachPodInterface field

_sidebar.md, misc/annotations_and_labels.md
Things to focus when reviewing:
- whether the index.html attachment makes sense (I couldn't find a better place to attach the info; and I didn't feel like creating more levels of embedding);
- an argument can be made that this information should be as close to API reference docs as possible (perhaps part of them).
Related to kubevirt/kubevirt#1080
=> Document annotations and labels of user interest

workloads/virtual-machines/disks-and-volumes.md
Document how IOThreads are getting pinned to pCPUs on VMIs with dedicated CPUs
Related to https://github.com/kubevirt/kubevirt/pull/1604
=> document IOThreads pinning to pCPUs

additional-resources.md
Was referencing Kubernetes instead of kubevirt
=> Fix link to kubevirt-incubator

workloads/virtual-machines/virtualized-hardware-configuration.md
Fixed broken link for CPU models that refers to a libvirt's github page.
=> Fix link to CPU models

_sidebar.md, workloads/templates/common-templates.md, workloads/virtual-machines/common-templates.md
This is the initial batch of documentation. More is still to come (also from @sHaggYcaT ).
I'm submitting this PR now because, albeit not complete, the initial changes are self-sufficient and allow us to bootstrap the "common-templates.md" file, which will receive more content later.
CC @sHaggYcaT @MarSik for reviews/comments
=> Document what users can do with the "common templates" subproject

workloads/virtual-machines/interfaces-and-networks.md
This is to align documentation with the kubevirt PR that adopts the
project to behavior expressed by the very latest sriovdp master:
https://github.com/kubevirt/kubevirt/pull/1692
=> Update sriov documentation to reflect the latest sriovdp master

workloads/virtual-machines/vmctl.md
Examples used an undefined serviceAccount. For the purposes of documentation, assume the default account has the correct permissions.
=> Remove references to vmctl ServiceAccount from examples

workloads/virtual-machines/interfaces-and-networks.md
With https://github.com/kubevirt/kubevirt/pull/1816 we no longer need to
fill in requests / limits for devices that implement sriov networks.
This patch updates the documentation to reflect that.
=> Update sriov docs to not include explicit device requests

workloads/virtual-machines/disks-and-volumes.md
Currently the links to sections of the doc are trying to use gh blob
references, but that doesn't actually work if you try and click on one
of the links.  The results is a 404.
Instead just use the GH MD syntax for internal doc links, that should
work and as as a bonus be portable for those that download the docs and are viewing
outside of GH or without net connectivity.
=> Fix indocument links in disk-and-volumes doc

workloads/virtual-machines/disks-and-volumes.md
The dataVolumeTemplate example is missing the required status parameter.
It seems like you should be able to have a default there and leave it
out, but the type definition for the object does not include an
omitempty tag so it must be included.
Fixes GH Issue: 168
=> Add status parameter to DataVolume example

administration/image-upload.adoc, architecture/virtual-machine.adoc, creating-virtual-machines/disks-and-volumes.adoc, creating-virtual-machines/virtio-win.adoc, docs/latest/administration/image-upload.html, docs/latest/creating-virtual-machines/disks-and-volumes.html
Cleanup _creationTimestamp: null_ from each kubevirt/kubernetes yaml manifest.
This MR was suggested in the conversation about another MR: https://github.com/kubevirt/user-guide/pull/150
=> cleanup creationTimestamp: null

creating-virtual-machines/dedicated-cpu.adoc, templates/common-templates.adoc
Added notice about sockets and threads in common templates and dedicated cpu section. 
@MarSik, @fabiand please can you review? Please feel free to point out, where the notice about sockets and threads is missing.
=> add socket and threads in templates and dedicated cpu

templates/common-templates.adoc
This PR wants to enhance the current, basic documentation of the common templates.
We want to show in this series how the user can customize the template themselves.
This is a continuation of https://github.com/kubevirt/user-guide/pull/165: I'm starting a new PR because
while PR#165 was in review, the repo undergone two major changes
1. layout reorganization
2. transition from md to adoc
Turns out the PR couldn't be easilly adapted (too many conflicts), so I'm starting again with the last content
=> templates: document the customization

creating-virtual-machines/virtio-win.adoc
Fixes issues in virtio example in user-guide: 
* missing space in example
* mixed case label
* provides clarification when to use bootOrder when mounting virtio
Fixes: #207
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/user-guide/210)
=> Fix errors in virtio user guide

administration/intro.adoc
Added note about changed kubevirt account which needs to be added to privileged SCC starting with Version 0.15.0.
I suggest another update once 0.15.0 is released, moving the new account into the normal documentation, and changing the note to mention the old account (or remove the note at all)
Signed-off-by: Marc Sluiter <msluiter@redhat.com>
=> Added note about changed kubevirt account 

creating-virtual-machines/interfaces-and-networks.adoc
Related to https://github.com/kubevirt/kubevirt/issues/1850#issuecomment-448792407 added some documentation about mac address configuration in the bridge interface type.
@fabiand @justinbarrick can you please take a look
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/user-guide/205)
=> Added documentation about mac address and virt-win

creating-virtual-machines/interfaces-and-networks.adoc
This update covers which plugins support `mac` attribute natively; which
work if combined with `tuning` plugin; and which are known to not work
at all. (The latter would require proper native support to be added in
the respective CNI code.)
=> Document how custom MAC address interacts with misc CNI plugins

administration/live-migration.adoc, administration/node-eviction.adoc
* Document cluster-wide migration limits and how to change them
* Document `evictionPolicy` for live-migrate on drains
=> Document live migration on node-drain

creating-virtual-machines/guest-operating-system-information.adoc
The merged kubevirt PR used a slightly different
name and approach for the HyperV strict checking,
so we make sure the documentation is up to date.
=> hyperv: sync with the last kubevirt changes

creating-virtual-machines/disks-and-volumes.adoc
Fixes the copy paste error in ContainerDisk documentation for custom path.
This lead to confusion for users how to properly use the custom disk path.
Now it is copy paste friendly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/user-guide/247)
=> Fix copy paste errors in constaineridsk doc

administration/intro.adoc
well known case, spawned from the discussion of
https://github.com/kubevirt/kubevirt/issues/2533
worth a mention in the docs.
=> update: warn about failed update for missing RBAC

creating-virtual-machines/disks-and-volumes.adoc
Document that containerdisks can be based on `scratch`, starting with kubevirt 0.20.
=> containerDisks on scratch

creating-virtual-machines/disks-and-volumes.adoc
* Fix confusing wording regarding to the use of a `base` image
* Delete paragraph which states that migrations don't work
* Replace "Registry Disk" with containerDisk.
=> Overhaul containerDisk documentation

creating-virtual-machines/interfaces-and-networks.adoc
With https://github.com/kubevirt/kubevirt/pull/2546 sriov is enabled by default and there is no need of setting the feature gate. This PR removes the instructions about setting the gate.
=> Remove info about sriov feature gate

administration/intro.adoc, docs/latest/administration/intro.html
Installation guide had a small typo (Terminatig -> Terminating)
=> Update typo in installation guide

creating-virtual-machines/interfaces-and-networks.adoc
in this PR we changed the example vm configuration
which had bridge as the default
binding method to masqurade.
That's regarding the issues discussed in detail here:
https://github.com/kubevirt/kubevirt/pull/2537
and here: https://github.com/kubevirt/kubevirt/pull/2493
We would like the examples to be consistent with
the changes suggested in those two PRs, and prevent from
a random user to copy-paste the examples and
receive an unexpected behavior.
=> Change examples with bridge to masquerade

administration/monitoring.adoc
Reflect in the docs the change `kubevirt_vm_` -> `kubevirt_vmi_`
=> monitoring: kubevirt metrics have been renamed

creating-virtual-machines/interfaces-and-networks.adoc
- A note was added, with example, on the flag that
allow us to disable and enable bridge interface
on pod network.
- A note was added suggesting the user to configure
masquerade as a default interface.
regards changes in this PR: 
https://github.com/kubevirt/kubevirt/pull/2493
=> Note and describe the option to disable bridge

administration/api-validation.adoc, administration/intro.adoc, administration/monitoring.adoc, administration/node-eviction.adoc, creating-virtual-machines/dedicated-cpu.adoc, creating-virtual-machines/interfaces-and-networks.adoc
The Web UI project is deprecated, the Web Console [1] is
extended for virtualization support.
[1] https://github.com/openshift/console
=> web-ui: Deprecate Web UI in favor of openshift/console

administration/monitoring.adoc
Documents https://github.com/kubevirt/kubevirt/pull/2573
There were a couple of user-facing notes changed, now that KubeVirt automatically creates the ServiceMonitor resource.
Signed-off-by: Stu Gott <sgott@redhat.com>
=> Update monitoring documentation to reflect current behavior

creating-virtual-machines/disks-and-volumes.adoc, using-virtual-machines/virtual-machine-replica-set.adoc, welcome/index.adoc
The alias `www.kubevirt.io` is currently broken (kubevirt/kubevirt.github.io#346), so the links that use it don't work.
This updates 3 links in the user guide to just use `kubevirt.io` instead of `www.kubevirt.io` as a workaround.
/kind bug
Fixes: #298
=> Update links to use kubevirt.io without www

creating-virtual-machines/dedicated-cpu.adoc
Signed-off-by: Vatsal Parekh <vparekh@redhat.com>
This explains the feature to define dedicated CPI for QEMU manager
Explains https://github.com/kubevirt/kubevirt/pull/2870/
=> Added user-guide for dedicated cpu for QEMU Emulator

creation/dedicated-cpu.md, creation/disks-and-volumes.md
Document how IOThreads will be pinned to the same pCPUs as the QEMU emulator thread on VMIs with dedicated CPUs.
Related to kubevirt/kubevirt#3103
=> document the IO and emulator threads pinning to a shared pCPUs

creation/disks-and-volumes.md
In our examples we need to highlight that the containerDisks need to be
readable by the qemu user (UID 107). Also our examples need to reflect
that.
xref: https://github.com/kubevirt/kubevirt/pull/3361
=> Explicitly set required permissions for containerDisk

creation/interfaces-and-networks.md
Use the cloud-init networkData section to configure the IP
addresses of the VM. Network data is evaluated before userData,
and as such, when the userData script kicks in, the IP
configuration is already in place.
It is also aestethically a lot nicer to configure the IP addresses
using this declarative format instead of by running a user side
script.
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>
=> ipv6, cloud-init: configure static ipv6 via networkData

_sidebar.md, usage/guest-agent.md
Add missing Guest Agent documentation.
The documentation add information from the PRs: kubevirt/kubevirt#2827 and kubevirt/kubevirt#3039
Signed-off-by: Petr Kotas <petr.kotas@gmail.com>
=> Add Guest agent usage documentation

creation/interfaces-and-networks.md
https://github.com/kubevirt/kubevirt/pull/3206 has dropped support for Genie. We should drop it from the user guide, too.
=> interfaces: drop Genie

OWNERS
Initial commit for OWNERS file
note: the tagging is set to the future user of mkdocs which will use directories docs and site.
See user-guide [issues/359](https://github.com/kubevirt/user-guide/issues/359)
=> Initial commit for OWNERS file

usage/virtual-machine-replica-set.md
Kubectl supports the `autoscale` command now for quite some time on CRDs: https://github.com/kubernetes/kubernetes/pull/72678.
=> kubectl autoscale works with VMIRS a long time now

creation/interfaces-and-networks.md
If `ports` are completely missing from a `masquerade` interface, all traffic is forwarded into the VM.
This was introduced in https://github.com/kubevirt/kubevirt/pull/2331 but not enshrined in the docs yet.
Signed-off-by: Dan Kenigsberg <danken@redhat.com>
=> networks: masquerade: default is forward all ports

creation/interfaces-and-networks.md
DHCP options belong into `interfaces.dhcpOptions` and not directly into
`interfaces`.
Fixes https://github.com/kubevirt/kubevirt/issues/4381
=> Fix dhcpOptions feature description

installation/image-upload.md
Current documentation to install CDI ([here](https://kubevirt.io/user-guide/#/installation/image-upload?id=install-cdi)) suggests deploying the `cdi-operator-cr.yaml` manifest. The correct file name should be `cdi-cr.yaml`, based on assets specified in https://github.com/kubevirt/containerized-data-importer/releases.
=> Fix manifest file name

installation/installation.md
A minor typo fix. The main thing here is changing the `VERSION` environment variable to `RELEASE` so that it's consistent with the updating and deleting doc. 
Signed-off-by: Aaron Sachs <aaronm.sachs@gmail.com>
=> Minor typo correction & change env var to be consistent with updating doc

creation/dedicated-cpu.md, creation/devices.md, creation/disks-and-volumes.md, creation/guest-operating-system-information.md, creation/interfaces-and-networks.md, installation/authorization.md, installation/installation.md, installation/live-migration.md, installation/node-eviction.md, usage/overcommit.md
This update shows the new way to configure kubevirt based on the PR https://github.com/kubevirt/kubevirt/pull/3455
=> remove references to kubevirt-config ConfigMap

creation/interfaces-and-networks.md
It is not possible to enable dedicatedCpuPlacement without
cpumanager enabled. Since we advertise the use of dedicatedCpuPlacement
in our sriov-vmi example, we should note the user about this dependency.
Signed-off-by: alonSadan <asadan@redhat.com>
=> user-guide, sriov: note about dedicatedCpuPlacement

creation/disks-and-volumes.md
Small fix: in the example yaml the `disk name` refers to the `disk1` volume while the name of the volume is defined as `volume1`.
=> datavolume: Refer to the proper volume name

docs/operations/containerized_data_importer.md
=> Spelling fix in CDI documentation

Makefile
`make build_image_userguide` didn't survive the build refactor from the other day.  The problem came from how we named the `project-infra/images/kubevirt-userguide` dir to store the Dockerfile.  We shot ourselves in the foot with that dir name.
This is an adjustment for that.
=> Fixed issue with userguide image name caused by build target refactor

docs/architecture.md, docs/virtual_machines/.pages, docs/virtual_machines/disks_and_volumes.md, docs/virtual_machines/guest_operating_system_information.md, docs/virtual_machines/replicaset.md, docs/virtual_machines/service_objects.md, docs/virtual_machines/startup_scripts.md, docs/virtual_machines/templates.md, docs/virtual_machines/virtual_machine_instances.md, docs/virtual_machines/windows_virtio_drivers.md, docs/welcome.md, mkdocs.yml
Fix failing links in content.  mkdocs build is now clean.
```
make: Warning: File 'Makefile' has modification time 0.59 s in the future
Makefile: Stop site
podman rm -f userguide 2> /dev/null; echo
Makefile: Run site
podman run -d --name userguide --net=host -v ./:/srv:ro --mount type=tmpfs,destination=/srv/site localhost/kubevirt-userguide:latest /bin/bash -c "mkdocs build -f /srv/mkdocs.yml && mkdocs serve -f /srv/mkdocs.yml -a 0.0.0.0:8000"
66c82bbb1529e19f49dd80eac6603f7ceefcdee955e7859b39e9f9f819fd6105
[root@fedora user-guide]# podman logs -f userguide
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /srv/site
INFO    -  Documentation built in 1.22 seconds
INFO    -  Building documentation...
WARNING -  Config value: 'dev_addr'. Warning: The use of …
```
=> Fix failing links in content

docs/architecture.md
Content only fixes for from PR 391
Signed-off-by: vados <vados@vadosware.io>
=> docs/architecture.md: typo fixes

docs/virtual_machines/host-devices.md
I suspect that the host device name in the VM spec must match the one
exposed by KubeVirt device plugin.
Please do not merge before approval by @vladikr.
=> host devices: case consistency

docs/operations/containerized_data_importer.md
Fix cdi cr yaml file broken download link according to [release page](https://github.com/kubevirt/containerized-data-importer/releases). 
Signed-off-by: clarkzjw <clarkzjw@gmail.com>
=> fix cdi cr download broken link

Makefile
HTMLProofer throws a warning regarding Gemfile.lock being read-only.  This file causes neverending issues so we volume mount `/dev/null` to the file.
I thought I fixed this before but it somehow slipped out.  So here is the patch again.
=> Fix to Gemfile.lock read-only warning

docs/virtual_machines/disks_and_volumes.md
The replaced text mislead a user, I hope that the suggestd one is
clearer about the bit that is not supported (update of ConfigMap disk
while VMI is running).
Signed-off-by: Dan Kenigsberg <danken@redhat.com>
=> disks: configmap: clarify sentence about update

docs/appendix/contributing.md
Bullets under prerequisites in the [User guide - Contributions page](https://kubevirt.io/user-guide/appendix/contributing/) are not listed correctly due to missing newlines.
=> Fix bullet lists in contributions page

docs/virtual_machines/dedicated_cpu_resources.md
Subsection [CPU Manager](https://kubevirt.io/user-guide/virtual_machines/dedicated_cpu_resources/) in Dedicated CPU Resources section of the user-guide seems to have many formatting issues. Have fixed lists and added headings to the best of my understanding.
Also, updated OCP link to later version (3.10 -> 4.6)
=> Fix markdown formatting in CPU Manager subsection in Dedicated CPU Resources

docs/architecture.md
This PR adds a description of the VirtualMachine's `status.printableStatus` field and its values.
This field is introduced in kubevirt/kubevirt#5528, which should be finalized and merged before this one gets merged.
Signed-off-by: Zvi Cahana <zvic@il.ibm.com>
=> Add description of VirtualMachine printableStatus field

docs/operations/virtctl_client_tool.md
Updated URL and version to latest, to download the virtctl linux client for 64-bit x86 processors. The current text references to the `linux-x86_64` os-arch pair, but the latest version [v0.41.0](https://github.com/kubevirt/kubevirt/releases/tag/v0.41.0) references it with [linux-amd64](https://github.com/kubevirt/kubevirt/releases/download/v0.41.0/virtctl-v0.41.0-linux-amd64).
```
$>export VERSION=v0.41.0
$> wget https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/virtctl-${VERSION}-linux-x86_64
--2021-05-21 21:02:38--  https://github.com/kubevirt/kubevirt/releases/download/v0.41.0/virtctl-v0.41.0-linux-x86_64
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 404 …
```
=> [FIX] Update virtctl_client_tool.md

docs/virtual_machines/.pages, docs/virtual_machines/boot_from_external_source.md
Add documentation for booting from external source which was enabled in this PR: https://github.com/kubevirt/kubevirt/pull/5416.
=> Add documentation for booting from external source

docs/operations/live_migration.md
How to disable TLS encryption for migrations for performance reasions. Also including a warning that this may allow MITM attacks.
Documents https://github.com/kubevirt/kubevirt/pull/5894
=> Document migrations without TLS

docs/operations/live_migration.md
When using VMI masquarade interface withany of the explicitly
specified ports 22222, 49152, 49153, live migration fails, because
all traffic destined to the said ports is forwarded
to the VM.
=> Document live-migration reserved ports

docs/virtual_machines/interfaces_and_networks.md
Document known limitation of macvlan network binding not providing seamless live-migration
=> document macvlan limitation for live-migration

docs/index.md
Removing https://github.com/kubevirt/demo and added links for 
- Katacoda scenarios as it  provides an live interactive demo.
- Quickstart labs as they are updated on a regular basis.
Fixes https://github.com/kubevirt/user-guide/issues/482
=> Updated the Try it Out! bullet point

docs/virtual_machines/interfaces_and_networks.md
This does not get formatted properly when used as a quote (note). By
removing the quote, the code block gets printed properly while it stills
stays in the middle of a note.
Signed-off-by: Petr Horáček <phoracek@redhat.com>
=> Fix snippet rendering of ptp-mac example

docs/virtual_machines/disks_and_volumes.md
=> Remove outdated reference to the deprecated kubevirt configmap

docs/virtual_machines/startup_scripts.md, docs/virtual_machines/windows_virtio_drivers.md
We moved to quay a long time ago and the virtio disk on dockerhub are
very outdated.
=> Fix virtio-containerdisk references

docs/virtual_machines/virtual_hardware.md
A couple of users asked about the support for memfd because they got the error `unsupported configuration: hugepages is not supported with memfd memory source`. This limitation is due to a too old host kernel. Adding this information could be useful to prevent other doubts.
=> add limitations when memfd is supported

docs/operations/updating_and_deletion.md
Documentation examples showed batchEvict{Size,Interval} instead of batchEviction{Size,Interval}.
=> Fix doc for batchEviction{Size,Interval}

docs/virtual_machines/interfaces_and_networks.md
The MAC address of the VMI is only propagated to the underlying CNI
for multus non default networks.
Fixes: https://github.com/kubevirt/kubevirt/issues/7055
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>
=> docs, network: clarify MAC setting on pod iface requires multus

docs/virtual_machines/virtual_hardware.md
The example for CPU resources had a request that was larger
than the limit, which doesn't really make sense.
Signed-off-by: Chris Friesen <chris.friesen@windriver.com>
=> Fix cpu resource request and limit (#519)

docs/virtual_machines/interfaces_and_networks.md
The text is currently not rendered correctly on the [0] web, since the
list entries are featuring extra spaces.
[0] - https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/#how-to-expose-host-interface-to-the-macvtap-device-plugin
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>
=> network, macvtap: fix markdown

docs/virtual_machines/interfaces_and_networks.md
There are recurring issues being created on KubeVirt related to some CNIs being used which we know do not work with our bridge binding option - the most common choice for secondary interfaces. 
Example issues: [[0](https://github.com/kubevirt/kubevirt/issues/5483)], [[1](https://github.com/kubevirt/kubevirt/issues/7001)], but there are more ...
For instance, we know that neither macvlan nor ipvlan plugins will work when the plugin configuration features IPAM for secondary bridge interfaces.
This commit adds a section to the user guide describing which plugins are known not work, along with a brief explanation of why.
=> docs, network: document bridge interface invalid CNIs

docs/virtual_machines/boot_from_external_source.md
Also, see this PR for implementation: https://github.com/kubevirt/kubevirt/pull/7530
=> [Kernel boot]: fix doc - kernel args without image is disallowed

docs/virtual_machines/interfaces_and_networks.md
The markdown was incorrectly added, thus causing the bullet lists to be
incorrectly rendered.
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>
=> network: fix markdown for invalid CNIs

docs/virtual_machines/virtual_hardware.md
Fix example in kubevirtCR to set obsoleteCPUModels with correct values.
https://kubevirt.io/api-reference/master/definitions.html#_v1_kubevirtconfiguration
=> Fix example in kubevirtCR to set obsoleteCPUModels with correct values

docs/operations/installation.md
Instead of pointing to a particular release, grab it from the kubevirt releases page.
Fixes: #543
=> docs, install guide: point to latest release rather than v0.35.0

docs/operations/snapshot_restore_api.md
KubeVirt is just able to snapshot the volume if the k8s volume
snapshot APIs that are persent in the cluster are being served
from v1 version. This commit explicitly specified that.
=> Update snapshot_restore docs to mention support for only v1 apis

docs/virtual_machines/interfaces_and_networks.md, docs/virtual_machines/istio_service_mesh.md
This PR is adding passt documentation explaining how to run a VM with passt interface.
It also updated the istio documentation to mention istio is now supported not only by masquerade VMs but by passt as well.
=> passt documentation

docs/virtual_machines/interfaces_and_networks.md
Add information about the multi queue queueCount field.
The new field describes how many queues were assigned
to each interface,
providing more details about the actual configured settings.
Related to https://github.com/kubevirt/kubevirt/pull/8071
=> multi queue: Introduce queueCount field

docs/operations/hotplug_volumes.md
Explain the current default 'persist' behavior
Add some explanation of why virtio-scsi instead of virtio
Signed-off-by: Alexander Wels <awels@redhat.com>
=> Update some of the hotplug documentation

docs/operations/containerized_data_importer.md
The current curl don't get the latest CDI version. The proposal is to read the "location" that curl receives in the 302 return of the request, and parses to get the tag in the URL.
Signed-off-by: Rafael Domiciano <rafael.domiciano@gmail.com>
=> Adjust on the get of the latest CDI tag version

docs/architecture.md
In the rendered docs this list is inlined because of a missing whitespace:
=> Fix list formatting in rendered docs (Application Layout)

docs/virtual_machines/interfaces_and_networks.md
The correct sysctl file-max contains a dash, instead of an underscore.
=> passt: fix sysctl file_max to file-max

docs/operations/export_api.md, docs/operations/memory_dump.md
This Pull Request updates the export API section in the user guide, so we cover the recently added `vmexport` command with examples and usage cases.
=> Update export API documentation to cover virtctl integration

docs/virtual_machines/liveness_and_readiness_probes.md
Yaml files of readiness and liveness examples have been updated to work with current kubevirt versions. Also, containerdisks images have been updated.
=> docs, probes: fix readiness and liveness examples

docs/virtual_machines/presets.md
/area instancetype
/cc @akrejcir 
This CRD has now been deprecated within KubeVirt [1] and will be removed
in a future release once the core API reaches v2 [2].
[1] https://github.com/kubevirt/kubevirt/pull/8069
[2] https://github.com/kubevirt/kubevirt/issues/8360
=> Mark VirtualMachineInstancePresets as deprecated

docs/virtual_machines/accessing_virtual_machines.md
Rework the Accessing Virtual Machines section by:
- Adding description for virtctl ssh and scp
- Simplifying the example YAML definitions
- Using consistent naming
- Various smaller improvements
=> Rework Accessing Virtual Machines section

docs/virtual_machines/tekton_tasks.md
add example how to enable deployTektonTaskResources feature gate in hco cr
tekton tasks are not deployed by default. This example shows user how to update feature gate to deploy tekton tasks.
Signed-off-by: Karel Šimon <ksimon@redhat.com>
=> add example how to enable deployTektonTaskResources feature gate in hco cr

docs/operations/installation.md
We don't use docker anymore anywhere and it is deprecated. But we use containerd via kind and a vendors use it too.
=> Update list of supported CRI implementations

docs/virtual_machines/.pages, docs/virtual_machines/vsock.md
This PR adds `VSOCK` section to user-guide.
I have copied `Background` section from the (vsock design proposal)[https://github.com/kubevirt/community/blob/main/design-proposals/vsock/vsock.md].
For now I haven't added a section for https://github.com/kubevirt/kubevirt/pull/8624, because the PR is not yet merged.
=> Adding VSOCK

docs/virtual_machines/interfaces_and_networks.md
When configuring passt binding with no explicit ports to forward, the memory overhead needed is added automatically, users no longer need to provide the VM with extra memory.
See https://github.com/kubevirt/kubevirt/pull/8716
=> passt: Remove note about extra memory when using passt

Makefile
Update to Makefile to avoid confusion between Netlify at 3.8 and our unified container at 3.10
=> Change to just python3 not a point release

docs/operations/installation.md
Making local modifications to the AppArmor profile works, but (where possible) uninstalling the libvirt package also does the trick and is a much simpler workaround, so recommend that.
=> apparmor: Recommend removing libvirt package

docs/virtual_machines/disks_and_volumes.md
The current example PVC uses a RWO access mode but if the point is to share this disk between multiple VMs then a RWX access mode would be more appropriate.
Signed-off-by: Adam Litke <alitke@redhat.com>
=> Disk sharing example PVC should use RWX access mode

docs/virtual_machines/instancetypes.md
/area instancetype
While 0af7617caa4513fe223107dc33165e86e4ae5296 updated the format of the data captured within a ControllerRevision it did not update the timing of when they are actually captured.
This change updates this section now that PR #8346 [1] has landed moving the creation of ControllerRevisions earlier in the reconcile loop.
[1] https://github.com/kubevirt/kubevirt/pull/8346
Signed-off-by: Lee Yarwood <lyarwood@redhat.com>
=> instancetype: Update versioning section

Makefile
The `which` binary is not installed in the container for back-end updates, and this is causing make to fail.
=> Removing ornamental which statement due to missing in container

docs/operations/scheduler.md
This PR adds an example detailing how to deploy secondary schedulers and how to schedule VMs using it.
=> Add an operation explaining how to deploy secondary schedulers.

docs/operations/snapshot_restore_api.md
To prevent confusion add explicitly the need to stop VM before being able to restore it
=> Add the need to stop VM before restore

docs/virtual_machines/instancetypes.md
Minor spelling error in instancetypes doc page.
Signed-off-by: John Harbin <john.harbin@cdw.com>
=> Fixed ClusterInstancetype spelling error in instancetypes

docs/operations/client_passthrough.md
- Clarify that the requeriments is to client side, by changing 'requirements' to 'requirements for virtctl usbredir'
- Add a bit of information of what is expected on client side when running 'virtctl usbredir'
- Fixes the markdown links.
Improves: https://github.com/kubevirt/user-guide/pull/635
Signed-off-by: Victor Toso <victortoso@redhat.com>
=> client-passthrough: Improve docs further

Makefile
Still bothers me that a `make run` would appear to be successfull
```
Makefile: Run site
podman run \
-d \
--name userguide \
-p 8000:8000 \
-v /home/toso/src/kubevirt/user-guide:/srv:ro \
-v /dev/null:/srv/Gemfile.lock:rw \
--mount type=tmpfs,destination=/srv/site \
localhost/kubevirt-user-guide \
/bin/bash -c "mkdocs build -f /srv/mkdocs.yml && mkdocs serve -f /srv/mkdocs.yml -a 0.0.0.0:8000"
1550257a2609c84964efdc1082bcfeedab9d171f7d431e3ac1847e10f8a8cf66
Makefile: Server now running at [http://localhost:8000]
```
When the actual result is
```
toso@tapioca ~/s/k/user-guide (fix-selinux-enabled)> podman ps
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
toso@tapioca ~/s/k/user-guide (fix-selinux-enabled)> podman container logs userguide
Usage: mkdocs …
```
=> Fix selinux enabled

docs/virtual_machines/lifecycle.md
According to [PR 5564](https://github.com/kubevirt/kubevirt/pull/5564), VirtualMachine renaming isn't supported anymore.
Signed-off-by: Marcelo Feitoza Parisi <marcelo@feitoza.com.br>
=> Remove virtctl rename

docs/virtual_machines/tekton_tasks.md
feat: update kubevirt tekton tasks documentation
This PR adds new task modify-windows-iso-file into KTT and updates names of example pipelines.
windows10-customize was renamed to windows-customize. 
Added documentation for new pipeline windows-efi-installer for win11/2k22
Signed-off-by: Karel Šimon <ksimon@redhat.com>
=> feat: update kubevirt tekton tasks documentation

docs/operations/hotplug_interfaces.md
Following kubevirt/kubevirt#9491, virtctl `addinterface` command arguments names were changed.
Align the docs to follow.
=> hotplug NIC: Rename virtctl addinterface arguments names

docs/operations/migration_policies.md
matchLabels was removed from migration policies spec in the following commit: https://github.com/kubevirt/kubevirt/pull/7510/commits/cab98e53fbaf0004299582c4617338d0ffa34950
This aligns with the code changes.
=> Remove "matchLabels" from Migration Policy spec

docs/operations/clone_api.md
Align user-guide: clone with a snapshot source is supported.
This supported was added as part of the following PR: https://github.com/kubevirt/kubevirt/pull/8458
=> Align user-guide: clone with a snapshot source is supported

docs/operations/gitops.md
This adds the 'Managing KubeVirt with GitOps' page to the Operations section. It contains a link to a demo on how to manage KubeVirt with GitOps.
=> Add Managing KubeVirt with GitOps page

docs/virtual_machines/interfaces_and_networks.md
The provided examples on the `interfaces and networks` section are using the macvlan plugin, which we later on list as something that doesn't work.
This commit provides a functional example to the user instead, which will provide a better experience to the user (it works, and it is not listed as not working later on).
Fixes: #678
=> network: remove macvlan examples

docs/operations/export_api.md
Explain the new 'manifests' field with the associated links for the manifest.
Explain the virtctl support for manifest so that it is easier to copy a VM to another cluster. Added example for this work flow.
=> Add documentation for vmexport manifests

docs/virtual_machines/disks_and_volumes.md
This PR adds details about how to use the enhancement introduced in https://github.com/kubevirt/kubevirt/pull/9432 to share ConfigMaps, Secrets, DownwardAPI and ServiceAccounts through Virtiofs.
=> Virtiofs, configvolumes: Add how to share configvolumes with virtiofs.

docs/operations/hotplug_interfaces.md
With https://github.com/kubevirt/kubevirt/pull/9844 , resources (e.g. PCI slots) are reserved for future hotplug.
The limitation section has been updated to reflect that.
---
Note: This should be merged only when the ref PR gets merged.
=> hotplug-interfaces: Update the limitation section with reserved ifaces

docs/virtual_machines/disks_and_volumes.md, docs/virtual_machines/startup_scripts.md
The documentation regarding Ignition is nearly non-existent. The only reference to it is a blog post [here](https://kubevirt.io/2018/ignition-support.html) which is not relevant anymore (see https://github.com/kubevirt/kubevirt/pull/9212 and the corresponding Slack conversation).
This PR add documentation about how to use Ignition with Kubevirt.
=> Add ignition documentation

docs/contributing.md
Moved "for code contributors" section to after general content, updated examples under "Try...", and added user-guide to "other ways" section.
=> Re-arrange contributor guide

docs/operations/hotplug_interfaces.md
The --persist option was removed. Any interface hotplug will be persisted.
=> hotplug interface: allowed only on VMs

docs/virtual_machines/instancetypes.md
Moves all instance type documentation to the new v1beta1 version.
=> instancetype: Move to v1beta1

docs/operations/live_migration.md
Since v0.56, with the PR:
https://github.com/kubevirt/kubevirt/pull/8047
=> live-migration: no need of feature gates

docs/virtual_machines/startup_scripts.md
When using the ConfigDrive datasource, the `networkData` part has to be in the [OpenStack Metadata Service Network](https://specs.openstack.org/openstack/nova-specs/specs/liberty/implemented/metadata-service-network-info.html) format.
Add an example of such a configuration.
Tested with CentOS stream {8,9} and RHEL {8,9}.
=> cloud-init, ConfigDrive: Add networkData example

docs/operations/installation.md
We have multi-arch images and binaries since the release 1.0. Update the document.
=> operation: add support of Arm64 platform in the installation page

docs/operations/export_api.md
This Pull Request aims to update the virtctl vmexport documentation, mainly to add coverage for the `port-forward` and `format` flags.
=> Export API: Update documentation with new vmexport flags

docs/virtual_machines/virtual_hardware.md
Super tiny change, just unindent the offending `features` section by one level.
=> Fix incorrect indentation for UEFI example (#696)

docs/virtual_machines/tekton_tasks.md
feat: add paragraph about deploying tekton pipelines in different namespace
This PR add a new paragraph to tekton documentation about deploying pipelines
in different namespace
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2227950
=> feat: add paragraph about deploying tekton pipelines in different namespace

docs/operations/live_migration.md
Also fixed the paragraph to render correctly in the mkdoc site.
=> ✏️ Fix typo in  live_migration page

docs/operations/updating_and_deletion.md
Currently, the list shows up like (note both points being rendered as 1):
<details>
<summary> old </summary>
</details>
This PR fixes it look like:
<details>
<summary> fixed </summary>
</details>
=> Fix ordered list in update doc

docs/operations/component_monitoring.md
Updated kubevirt_vmi_vcpu_seconds to
kubevirt_vmi_vcpu_seconds_total based on
PR https://github.com/kubevirt/kubevirt/pull/9821
=> update metric name

docs/virtual_machines/disks_and_volumes.md
Document the option introduced by https://github.com/kubevirt/kubevirt/pull/10058 to configure the error policy for disks and luns
=> Document how to use the error policy

docs/virtual_machines/dedicated_cpu_resources.md
Following kubevirt/kubevirt#10593 it is possible to run VMs with dedicated CPU placement and emulator thread isolation on compute nodes with SMT [1] enabled and `full-pcpus-only` CPUManager policy [2].
This configuration is used for high-performance VMs.
Add an explanation on how to use it.
[1] https://en.wikipedia.org/wiki/Simultaneous_multithreading
[2] https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#static-policy-options
=> IsolateEmulatorThread with full-pcpus-only

docs/virtual_machines/interfaces_and_networks.md
Indicate a VM with a pod network of masquerade type should be exposed as a service.
Indicate a VM with a pod network of masquerade type is contacted using the pod's IP address when not exposed by a service.
Fixes: #737
=> network: masquerade improvements

docs/.pages, docs/debug_virt_stack/.pages
Add pages for the new section about virtualization stack debugging added by https://github.com/kubevirt/user-guide/pull/725
=> Add pages for new section about virt debugging

docs/virtual_machines/.pages, docs/virtual_machines/interfaces_and_networks.md, docs/virtual_machines/net_binding_plugins/passt.md, docs/virtual_machines/net_binding_plugins/slirp.md, docs/virtual_machines/network_binding_plugins.md
Describe the network binding plugins infrastructure for users.
Includes detailed explanation with examples.
The following binding plugins are included:
- Passt
-  slirp binding plugin
In follow up PRs, the following subject should be covered:
- Domain Attachement
- macvtap binding plugin
=> docs, vm: Add network binding plugins guide

docs/virtual_machines/dedicated_cpu_resources.md
Revert changes made by PR #736.
PR https://github.com/kubevirt/community/pull/247 now proposes a different approach.
=> Revert "IsolateEmulatorThread with full-pcpus-only (#736)"

docs/virtual_machines/interfaces_and_networks.md, docs/virtual_machines/net_binding_plugins/macvtap.md, docs/virtual_machines/network_binding_plugins.md
Update the user guide with the new domain attachment type option for network binding plugins and the usage of it when using macvtap binding.
=> docs, vm, network binding plugins: The network domain attachment option and its usage with macvtap

docs/operations/hotplug_volumes.md
LUN support for hotplug volumes was recently implemented in https://github.com/kubevirt/kubevirt/pull/10529. This PR updates the user-guide documentation to add coverage for this feature.
=> Update volume-hotplug documentation to cover LUN support

docs/virtual_machines/dedicated_cpu_resources.md
PR kubevirt/kubevirt#10872 added a cluster-wide setting that makes it possible to run
VMs with dedicated CPU placement and emulator thread isolation on compute nodes with SMT [1] enabled and `full-pcpus-only` CPUManager policy [2].
This configuration is used for high-performance VMs.
Add an explanation on how to use it.
[1] https://en.wikipedia.org/wiki/Simultaneous_multithreading
[2] https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#static-policy-options
=> IsolateEmulatorThread: Complete to even parity

OWNERS
I would like to be more helpful with reviews for the user-guide.
To date I have helped review [16 PRs in this repo](https://github.com/kubevirt/user-guide/pulls?q=is%3Apr+reviewed-by%3Aaburdenthehand+is%3Aclosed+), and created [13 PRs that have been merged](https://github.com/kubevirt/user-guide/pulls?q=is%3Apr+author%3Aaburdenthehand+is%3Aclosed).
=> Add aburden as reviewer for user guide

docs/virtual_machines/dedicated_cpu_resources.md
PR #745 introduced the `Compute Nodes with SMT Enabled` section.
The ordered and unordered lists in it are not rendered correctly when viewed from kubevirt.io.
Add a newline before a list begins.
Preview:
https://deploy-preview-754--kubevirt-user-guide.netlify.app/virtual_machines/dedicated_cpu_resources/#compute-nodes-with-smt-enabled
=> Dedicated CPU placement: Fix list rendering

docs/virtual_machines/disks_and_volumes.md
It explains how to enable and disable PVC privileged and non-privileged sharing modes thought virtiofsd. It also explains the limitations of each mode.
Feature added in: https://github.com/kubevirt/kubevirt/pull/10657
=> virtiofs: adds non-privileged virtiofsd sharing

OWNERS
@mazzystr has left the project a while ago, so we are moving him to emeritus.
/cc @aburdenthehand
=> Move mazzystr to emeritus

docs/virtual_machines/accessing_virtual_machines.md
Replace instances of cloudInitConfigDrive / configDrive with
cloudInitNoCloud / noCloud, since cloud-init NoCloud is the preferred
way to deliver cloud-init configuration data and it is now supported
by the access credentials api.
Fixes #
**Checklist**
```release-note
None
```
=> Accessing Virtual Machines: Switch to cloudInitNoCloud

docs/virtual_machines/creating_vms.md, docs/virtual_machines/instancetypes.md
Document the behavior of inferFromVolumeFailurePolicy and the inference by default in virtctl create vm.
Fixes #
**Checklist**
```release-note
None
```
=> instancetypes: Document inferFromVolumeFailurePolicy

docs/virtual_machines/interfaces_and_networks.md
Update the 'Interface And Networking' docs, Multus example to use bridge CNI.
Fixes #
**Checklist**
```release-note
```
=> networking: Update Multus example to use bridge CNI

docs/virtual_machines/net_binding_plugins/passt.md, docs/virtual_machines/network_binding_plugins.md
Add migration API to the network binding plugin docs.
Also update the passt docs to specify it supports migration.
Fixes #
**Checklist**
```release-note
```
=> Add migration API to the network binding plugin docs

docs/virtual_machines/interfaces_and_networks.md
SR-IOV doc fixes
- fix reference to vfio-pci devicetype: `driver: vfio` is not valid (you will see `driver: vfio-pci ` in the `SriovNetworkNodeState` however in the policy it is `deviceType: vfio-pci`)
- sriov-network-operator - swap `openshift` for `k8snetworkplumbingwg` ([k8snetworkplumbingwg](https://github.com/k8snetworkplumbingwg/sriov-network-operator) is upstream from [openshift](https://github.com/openshift/sriov-network-operator) repo now and should be considered the authoritative source)
Fixes #
**Checklist**
This checklist is not enforcing, but …
=> SR-IOV doc fixes

docs/virtual_machines/virtual_hardware.md
The corresponding feature gate `CPUNodeDiscovery` is now enabled by default, hence the section is not needed anymore.
https://github.com/kubevirt/kubevirt/pull/7728
Fixes #
**Checklist**
```release-note
NONE
```
=> Drop 'Enabling cpu compatibility enforcement'

docs/operations/.pages, docs/operations/cpu_hotplug.md, docs/operations/memory_hotplug.md, docs/operations/vm_rollout_strategies.md
Updating CPU hotplug documentation and add a pages about VM rollout strategies
Fixes #
**Checklist**
```release-note
NONE
```
=> VM rollout strategy

docs/operations/virtctl_client_tool.md
The current version reported in the guide is quite old and the users should try to install the latest version of virtctl when possible.
Update the documentation to fetch the latest virtctl version
```release-note
NONE
```
=> virtctl: use the stable version for virtctl

docs/operations/hook-sidecar.md
with https://github.com/kubevirt/kubevirt/pull/11272 image field becomes optional in the hook sidecar annotation since, if omitted, virt-controller will now use
a default sidecar-shim image built with other kubevirt images.
Fixes #775 
No to retrieve the version of the hook sidecar shim version from kubevirt CR, the virt-controller can now autonomously handle it. 
**Checklist**
```release-note
image …
```
=> image field in hook sidecar annotation is optional

docs/virtual_machines/disks_and_volumes.md
The disk expansion feature is documented in [kubevirt/kubevirt/docs/disk-expansion](https://github.com/kubevirt/kubevirt/blob/main/docs/disk-expansion.md) , but it is missing in the user-guide.
Fixes #
**Checklist**
```release-note
Document disk expansion in the user-guide
```
=> volumes: move the disk expansion documentation

docs/virtual_machines/tekton_tasks.md
chore: clean up of kubevirt tekton tasks section
this commit cleans up the kubevirt tekton tasks section. It removes the sections about deployment with ssp operator and adds paragrap about tasks and pipelines being available in artifacthub.
**Checklist**
```
Update KubeVirt Tekton Tasks section
```
=> chore: clean up of kubevirt tekton tasks section

docs/storage/disks_and_volumes.md, docs/storage/hotplug_volumes.md, docs/user_workloads/instancetypes.md, docs/user_workloads/startup_scripts.md, docs/user_workloads/templates.md
Replaces DataVolume PVC target with the newer storage target.
This is the modern API we want users to be using. It also allows for skipping certain parameters due to better defaults.
**Checklist**
```release-note
NONE
```
=> Replace usage of DataVolume.spec.pvc with .storage

docs/network/hotplug_interfaces.md
The network hotplug feature has been available since Kubevirt v1.1 as Alpha.
There have been no changes in the API since and the feedback from users has been positive.
Therefore, the feature is declared Beta towards v1.3 and should be proposed for GA towards v1.4.
Fixes #
**Checklist**
```release-note
NONE
```
=> operations, network: Declare network hotplug feature as Beta

docs/compute/node_assignment.md
This PR documents the interractions between node selector / affinities and the LiveUpdate VM rollout strategy.
Fixes #
**Checklist**
```release-note
NONE
```
=> node assignment: add paragraph about live updates

docs/debug_virt_stack/privileged-node-debugging.md
Fix a simple typo: ymal => yaml
```release-note
NONE
```
=> Fix typo: ymal ⇒ yaml

docs/network/net_binding_plugins/passt.md
Following PR https://github.com/kubevirt/kubevirt/pull/12235, it is now possible to specify memory overhead for the virt-launcher's compute container.
Instruct users of the passt binding plugin to register it with a memory overhead of 500Mi for the compute container.
Fixes #
**Checklist**
```release-note
None
```
=> passt: Add memory overhead

docs/network/network_binding_plugins.md
Following PR kubevirt/kubevirt#12235, it is now possible to specify memory overhead for the virt-launcher's compute container.
Add an explanation about the compute resource overhead in general, with a note that only memory overhead request is currently supported.
Fixes #
**Checklist**
```release-note
None
```
=> Network binding plugins: Add compute resource overhead

OWNERS, OWNERS_ALIASES, docs/cluster_admin/OWNERS, docs/compute/OWNERS, docs/debug_virt_stack/OWNERS, docs/network/OWNERS, docs/storage/OWNERS
Since we have the sigs formed for the several topics, let's establish ownership of the sections by each respective sig.
This PR adds and `OWNERS_ALIASES` file to capture the several aliases, copying from kubevirt/kubevirt. Also it adds `OWNERS` that refer to those sig groups, so that the groups can own the changes to the user-guide themselves.
Also it removes some users from the reviewers section who haven't shown
review activity for the last six months - this way we avoid assigning
them to the reviews and getting reviews stalled.
See https://kubevirt.devstats.cncf.io/d/46/pr-reviews-by-contributor?orgId=1&var-period=d7&var-repo_name=kubevirt%2Fuser-guide&var-reviewers=%22davidvossel%22&var-reviewers=%22rmohr%22&var-reviewers=%22stu-gott%22 
**Which …
=> owners, user-guide: set up owners from sigs

docs/compute/numa.md
This fixes a typo in the yaml path for configuring NUMA GuestMappingPassthrough.
fixes #815
**Checklist**
```release-note
NONE
```
=> Fix typo in path for numa guestMappingPassthrough

docs/user_workloads/virtctl_client_tool.md
if user launch `export VERSION==$(curl https://storage.googleapis.com/kubevirt-prow/release/kubevirt/kubevirt/stable.txt)` gets `=v1.2.1` value, which is invalid to download binary from storage
Fixes #
**Checklist**
```release-note
```
=> docs: remove one "=" sign from export VERSION to fix virtctl installation 

docs/compute/resources_requests_and_limits.md
Context implies multiplication but lack of spaces turns it into italics
Fixes #
**Checklist**
```release-note
```
=> Fix Markdown formatting

docs/storage/disks_and_volumes.md
cdrom readonly field is `readonly` not `readOnly` - see: https://github.com/kubevirt/kubevirt/blob/6c25e0e56eef200423811486523d9863e3f9ea79/staging/src/kubevirt.io/api/core/v1/schema.go#L702
=> fix cdrom readonly field

docs/user_workloads/instancetypes.md
Fixes #
**Checklist**
```release-note
NONE
```
=> instancetypes: Add PreferredCPUTopology and SpreadOptions docs

docs/cluster_admin/installation.md
Add instructions on how to use the nightly builds for s390x architecture.
Fixes #
I have considered making the arm64 section more generic instead, but ultimately decided it would make the instructions needlessly compilecated.
**Checklist**
```release-note
Add instructions for using kubevirt s390x developer builds
```
=> installation: Add guide for using s390x developer builds

docs/user_workloads/creating_vms.md
This documents how to use virtctl create vm to infer an instancetype or preference from another volume than virtual machine's boot volume.
Fixes #
**Checklist**
```release-note
None
```
=> Creating VirtualMachines: Describe inference from volumes

docs/compute/live_migration.md
`completionTimeoutPerGiB` can be used to either abort a migration or switch it to post-copy. This PR adds a documentation for the post-copy usage.
```release-note
NONE
```
=> completionTimeoutPerGiB: can be used to trigger post-copy migrations

docs/compute/live_migration.md
Following https://github.com/kubevirt/kubevirt/pull/13018, it is possible to have a VM whose primary NIC is connected to a pod NIC with a name other than `eth0`.
In order for the migration to be successful, it is required for the both the source and target virt-launcher pods
to have the same primary NIC name, for example: `eth0`.
[1] https://github.com/kubevirt/community/pull/324
Fixes #
**Checklist** …
=> Live Migration: Add primary pod NIC name limitation

docs/network/hotplug_interfaces.md
The network hotplug feature has been available since Kubevirt v1.1 as Alpha, followed in v1.3 as Beta.
There have been no changes in the API since and the feedback from users has been positive.
Therefore, the feature is declared GA towards v1.4.
Fixes #
**Checklist**
```release-note
NONE
```
=> operations, network: Declare network hotplug feature as GA

docs/network/network_binding_plugins.md
Introduce a limited support for an individual network binding plugin.
Fixes #
**Checklist**
```release-note
NONE
```
=> docs, network, binding-plugins: Add a limited support note and bump to Beta

docs/architecture.md, docs/cluster_admin/ksm.md, docs/cluster_admin/scheduler.md, docs/compute/numa.md, docs/compute/run_strategies.md, docs/network/hotplug_interfaces.md, docs/network/net_binding_plugins/macvtap.md, docs/network/net_binding_plugins/passt.md, docs/network/net_binding_plugins/slirp.md, docs/network/network_binding_plugins.md, docs/storage/disks_and_volumes.md, docs/storage/export_api.md, docs/user_workloads/accessing_virtual_machines.md, docs/user_workloads/instancetypes.md, docs/user_workloads/pool.md, docs/user_workloads/startup_scripts.md, docs/user_workloads/templates.md
Change deprecated spec.running references to runStrategy.
**Which issue(s) this PR fixes**:
jira-ticket: https://issues.redhat.com/browse/CNV-45433
```release-note
Change deprecated spec.running references to runStrategy
```
=> Change spec.running refs to runStrategy

docs/compute/live_migration.md
Fix one typo in a manifest example that is technically incorrect
In addition, improve grammar in text to make it more concise 
Fixes #
**Checklist**
```release-note
NONE
```
=> compute, live-migrations: fix typo and improve grammer

docs/storage/clone_api.md
Reflect the fact that VMsnapshots are already supported as clone source.
```release-note
Reflect the fact that VMsnapshots are already supported as clone source
```
=> Reflect the fact that VMsnapshots are already supported as clone source

docs/user_workloads/creating_vms.md
Change the virtctl create vm examples to use the correct flag for adding a sysprep volume to a created VM.
Fixes #
**Checklist**
```release-note
None
```
=> fix(virtctl): Use correct flag for sysprep volume in example

docs/compute/persistent_tpm_and_uefi_state.md
Update [Persistent TPM and UEFI state](https://kubevirt.io/user-guide/compute/persistent_tpm_and_uefi_state/#backend-storage) to reflect the changes made in https://github.com/kubevirt/kubevirt/pull/11773
~Also, small spelling fix: prerequesites -> prerequisites~ (fixed in #846)
Fixes #
**Checklist**
```release-note
```
=> Update persistent TPM & UEFI page to clarify storageclass requirements

docs/user_workloads/deploy_common_instancetypes.md
/cc @jcanocan 
The FG controlling the common-instancetypes deployment feature has GA'd with KubeVirt v1.4.0 so remove the reference and update our docs.
Fixes #
**Checklist**
```release-note
NONE
```
=> common-instancetypes: Remove FG and update docs

docs/cluster_admin/migration_policies.md
**What this PR does / why we need it**: Fix a wrong indentation in a few yaml examples in the [Migration Policies documentation](https://kubevirt.io/user-guide/cluster_admin/migration_policies/#api-examples)
**Checklist**
=> (migration_policies) fix wrong spec indentation

docs/user_workloads/startup_scripts.md
Fixes https://github.com/kubevirt/kubevirt/issues/12707
**Checklist**
```release-note
NONE
```
=> chore: replace device name for disks with bus type virtio as dev name is unsupported

docs/storage/disks_and_volumes.md
Change [#11997](https://github.com/kubevirt/kubevirt/pull/11997/) introduces new feature gates for virtiofs and dropped the support of privileged sharing mode. It syncs the documentation to the mentioned change:
* Users need to enable the feature gate `EnableVirtioFsConfigVolumes` for sharing `configMaps`, `secrets`, and `serviceAccounts`.
* Users need to enable the feature gate `EnableVirtioFsStorageVolumes` for sharing `PVCs`.
* Dropped support of privileged sharing mode.
Moreover, change [#13756](kubevirt/kubevirt#13756) enables to migrate VMs while sharing devices with virtiofs. Therefore, all mentions to live migration limitation has been dropped.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …
=> virtiofs: Update feature gate usage, privileged containers and live migration

docs/storage/clone_api.md
To align with: https://github.com/kubevirt/kubevirt/pull/13520
```release-note
Change clone API version from v1alpha1 to v1beta1
```
=> Change clone API version from v1alpha1 to v1beta1

docs/storage/.pages, docs/storage/volume_migration.md
Update the volume migration with the information about the volume migration cancellation and recovery. Additionally, it also fix the title of the document
```release-note
NONE
```
=> Update volume migration doc

docs/network/interfaces_and_networks.md
Add documentation for the link state management feature.
Fixes #
**Checklist**
```release-note
NONE
```
=> network: Add link state management section

docs/network/interfaces_and_networks.md
The current documentation is incorrect. It indicates that the ports attribute  serves as some sort of firewall, when in fact is has a different effect on each  net binding. It is basically either a list of ports to forward or it has no effect   at all.
Fixes #
**Checklist**
```release-note
NONE
```
=> net, ifaces: Fix ports section

docs/compute/resources_requests_and_limits.md
As it is GAed already
Fixes #
**Checklist**
```release-note
NONE
```
=> Remove docs regarding AutoResourceLimits FeatureGate

docs/network/service_objects.md
- Update the VM instead of VMI when exposing service objects
Fixes #698
**Checklist**
```release-note
None
```
=> Update VM instead of VMI when exposing service objects

docs/user_workloads/.pages, docs/user_workloads/legacy_windows.md
This adds documentation for the kubevirt.io/disablePCIHole64 annotation, that allows to run legacy Windows versions on KubeVirt.
Fixes #
**Checklist**
```release-note
None
```
=> Document how to run legacy Windows versions

docs/storage/clone_api.md, docs/storage/snapshot_restore_api.md
There's missing features in the documentation of VMRestores:
- target readiness policies
- patches
This was brought to my attention in this issue https://github.com/kubevirt/kubevirt/issues/14588 by @iholder101 
Now every feature available is documented:
```go
// VirtualMachineRestoreSpec is the spec for a VirtualMachineRestoreresource
type VirtualMachineRestoreSpec struct {
// initially only VirtualMachine type supported
Target corev1.TypedLocalObjectReference `json:"target"`
VirtualMachineSnapshotName string `json:"virtualMachineSnapshotName"`
// +optional
TargetReadinessPolicy …
```
=> chore(doc): document missing features in vmsnapshotrestores

docs/compute/cpu_hotplug.md
PR kubevirt/kubevirt#14728, enabled CPU hotplug with network multi-queue.
The fix was backported to release-1.5 [1] and release-1.4 [2].
[1] https://github.com/kubevirt/kubevirt/pull/14762
[2] https://github.com/kubevirt/kubevirt/pull/14763
Fixes #
**Checklist**
```release-note
NONE
```
=> CPU hotplug: Add net multi-queue limitation

docs/network/hotplug_interfaces.md
- Add a note about VMIM hardening in NIC hotplug docs
Fixes #885 
**Checklist**
```release-note
None
```
=> Add a note about VMIM hardening in NIC hotplug docs

docs/user_workloads/instancetypes.md
Fixes #
**Checklist**
```release-note
NONE
```
=> instancetype: Clean up docs ahead of v1.6.0 release

docs/network/hotplug_interfaces.md
Starting KubeVirt 1.6, the VM will be automatically migrated on hotplug and hot-unplug scenarios.
[1] https://github.com/kubevirt/kubevirt/pull/14259
Fixes #
**Checklist**
```release-note
NONE
```
=> net, hotplug: Add note about auto migration

docs/cluster_admin/installation.md
/cc @dhiller 
We now provide these arch specific images under a single nightly manifest allowing users to use the same set of commands to install our nightly builds across amd64, arm64 and s390x.
Fixes #
**Checklist**
```release-note
NONE
```
=> cluster_admin: Remove s390x and arm64 specific nightly installation docs

docs/compute/persistent_tpm_and_uefi_state.md
This PR adds storage class and storage profile configuration details to the persistent tpm docs. This is needed so that users are aware of kubevirt persistent tpm volume defaulting and selection logic for access mode.  
My team had a use case where we had a 2 node cluster and were using the local path provisioner storage class which only works with a RWO access mode. It was difficult to understand why we never saw a persistent volume created until we dug into the kubevirt go source (you can see the persistent tpm access mode logic [here](https://github.com/kubevirt/kubevirt/blob/v1.5.2/pkg/storage/backend-storage/backend-storage.go#L420)) and realized how access mode is being calculated for the VirtualMachine's persistent tpm volume.
=> docs(compute): update persistent_tpm_and_uefi_state.md

docs/cluster_admin/confidential_computing.md
Add guidance needed for running IBM Secure Execution VMs on s390x. Skip describing how to create the workload as this is specific to the user workload.
Add guide to deploying Secure Execution VMs on s390x
Fixes #
**Checklist**
```release-note
NONE
```
=> confidential computing: Add guide for running IBM Secure Execution VM

docs/storage/disks_and_volumes.md, docs/storage/hotplug_volumes.md
Docs for:
https://github.com/kubevirt/kubevirt/pull/13847
https://github.com/kubevirt/kubevirt/pull/14754
https://github.com/kubevirt/kubevirt/pull/14907
Fixes #
**Checklist**
```release-note
Update docs for declarative hotplug with virtio bus support
```
=> Update docs for declarative hotplug with virtio bus support

docs/user_workloads/accessing_virtual_machines.md
virtctl now only supports wrapping local ssh and scp clients. The --local-ssh flag was dropped, therefore remove it from the user guide.
Fixes #
/hold
Merge after https://github.com/kubevirt/kubevirt/pull/15478
**Checklist**
```release-note
None
```
=> accessing_virtual_machines: Remove virtctl local ssh flag
